//! Component Model bindings generated by wasmtime from the WIT (M4-P2).
//!
//! The WIT is THREE packages since ADR 0041 decision 4 (`norte:host`,
//! `norte:plugin`, `norte:provider`), so `path` points at the `wit/`
//! DIRECTORY — not a file — and wasmtime resolves `wit/deps/` on its own. The
//! worlds that live outside the package above are named in full
//! (`norte:provider/norte-provider`).
#![allow(missing_docs)] // generated code carries no rustdoc

wasmtime::component::bindgen!({
    world: "norte-plugin",
    path: "wit",
});

/// Bindings for the `norte-provider` world (#30 stage 2). In its own module
/// to avoid colliding with `norte-plugin`'s types; it REUSES the `host-log`
/// and `host-config` interfaces (P2 Task 3) from the world above (`with`) so
/// as not to duplicate the `Host` trait or `add_to_linker` —
/// [`crate::runtime::HostState`] implements them once.
///
/// The world is named IN FULL: from the package partition it lives in
/// `norte:provider`, not in the package above.
pub mod provider_world {
    wasmtime::component::bindgen!({
        world: "norte:provider/norte-provider",
        path: "wit",
        with: {
            "norte:host/host-log": crate::bindings::norte::host::host_log,
            "norte:host/host-config": crate::bindings::norte::host::host_config,
        },
    });
}

/// Bindings for the `norte-decorator` world (ADR 0037 decision 2). Same
/// reason for a separate module + `with:` as [`provider_world`]: not to
/// duplicate the `host-log`/`host-config` `Host` trait or its
/// `add_to_linker`.
pub mod decorator_world {
    wasmtime::component::bindgen!({
        world: "norte-decorator",
        path: "wit",
        with: {
            "norte:host/host-log": crate::bindings::norte::host::host_log,
            "norte:host/host-config": crate::bindings::norte::host::host_config,
        },
    });
}

/// Bindings for the `norte-columns` world (ADR 0037 decision 2). Same
/// pattern as [`decorator_world`].
pub mod columns_world {
    wasmtime::component::bindgen!({
        world: "norte-columns",
        path: "wit",
        with: {
            "norte:host/host-log": crate::bindings::norte::host::host_log,
            "norte:host/host-config": crate::bindings::norte::host::host_config,
        },
    });
}

pub mod renamer_world {
    wasmtime::component::bindgen!({
        world: "norte:renamer/norte-renamer",
        path: "wit",
        with: {
            "norte:host/host-log": crate::bindings::norte::host::host_log,
            "norte:host/host-config": crate::bindings::norte::host::host_config,
            // The SAME location interface as the columns world: a single
            // `LocationHost` serves both.
            "norte:location/location": crate::bindings::columns_world::norte::location::location,
        },
    });
}

/// Bindings for the `norte-organizer` world (phase 8, package
/// `norte:organizer`). The exact same pattern as [`renamer_world`], because
/// it is its sibling: the only thing that changes is that each proposal's
/// destination is a relative path rather than a name.
pub mod organizer_world {
    wasmtime::component::bindgen!({
        world: "norte:organizer/norte-organizer",
        path: "wit",
        with: {
            "norte:host/host-log": crate::bindings::norte::host::host_log,
            "norte:host/host-config": crate::bindings::norte::host::host_config,
            "norte:location/location": crate::bindings::columns_world::norte::location::location,
        },
    });
}

/// Bindings for the `norte-hook` world (H1, ADR 0100). Same pattern as
/// [`renamer_world`]: the three imported interfaces are the other worlds',
/// served by the same `HostState`.
pub mod hook_world {
    wasmtime::component::bindgen!({
        world: "norte:hook/norte-hook",
        path: "wit",
        with: {
            "norte:host/host-log": crate::bindings::norte::host::host_log,
            "norte:host/host-config": crate::bindings::norte::host::host_config,
            "norte:location/location": crate::bindings::columns_world::norte::location::location,
        },
    });
}

/// The world of a THUMBNAIL plugin (ADR 0107, package `norte:thumbnail`):
/// exports `thumbnail` and imports `host-log` and `host-config`, the same
/// ones from the main world and served by the same `HostState`. No
/// `location`: it receives the bytes, not a path.
pub mod thumbnail_world {
    wasmtime::component::bindgen!({
        world: "norte:thumbnail/norte-thumbnail",
        path: "wit",
        with: {
            "norte:host/host-log": crate::bindings::norte::host::host_log,
            "norte:host/host-config": crate::bindings::norte::host::host_config,
        },
    });
}

/// The world of a PANEL plugin (phase 3 of the 2026-09-15 program, package
/// `norte:panel`): exports `panel` and imports the usual three interfaces,
/// served by the same `HostState`.
///
/// WITH `location`, unlike the thumbnail one: a useful panel almost always
/// reads something about where it is — the `.git` branch, a `README` — and
/// that is the scoped, audited capability it does it with. Without it, it
/// could only paint what the context tells it.
pub mod panel_world {
    wasmtime::component::bindgen!({
        world: "norte:panel/norte-panel",
        path: "wit",
        with: {
            "norte:host/host-log": crate::bindings::norte::host::host_log,
            "norte:host/host-config": crate::bindings::norte::host::host_config,
            "norte:location/location": crate::bindings::columns_world::norte::location::location,
        },
    });
}
