//! Navigation model of the help overlay (H3b): which topics the sidebar
//! shows, which one is open, what the filter keeps, where the reader has
//! been, and which action the cursor is on.
//!
//! Lives here and not in `norte-tui` for the reason the settings model (S4)
//! and the palette rows (G3c) live here: the GUI view of H3f is the SAME
//! model with a different painter, and a second copy in `norte-gui` would
//! drift from this one within a phase. Nothing in this module knows about
//! ratatui, GPUI or a terminal cell.
//!
//! Nothing here is user-facing text either: what comes out is ids and tags
//! (`SidebarRow::Group.tag`, [`Action::Run`]'s command id), and the frontend
//! turns each one into a Fluent string. That is what lets one model serve two
//! frontends that name the same thing differently.

use std::collections::{BTreeMap, BTreeSet};

use norte_encoding::mask_terminal_hazards;
use norte_help::{Lang, Origin, Topic, TopicId, topics};

/// Id of the topic the overlay opens on.
const INDEX_ID: &str = "index";

/// Id of the synthetic keyboard page.
///
/// Not a corpus topic: its body is the effective keymap, generated by the
/// frontend (`norte_tui::help::build`), so it cannot be prose in a `.md`
/// file. It gets an id anyway because the sidebar, the history and the
/// filter all address entries by id, and a special case in each of them
/// would be three places to forget. H3h may replace it with a real topic;
/// nothing outside this module has to change if it does.
///
/// Having no corpus entry, it also has no corpus TITLE: the frontend hands
/// its localized label to [`HelpState::new`] and the row carries it like any
/// other title, so the filter reaches this page by the name it is painted
/// with (`teclado` finds it in Spanish) without this module ever touching
/// Fluent. The id stays a match too, and is the fallback when a frontend
/// passes a blank label.
pub const KEYS_ID: &str = "keys";

/// Tag the keyboard page is grouped under.
const KEYS_TAG: &str = "keys";

/// Tag the plugin pages are grouped under.
const PLUGINS_TAG: &str = "extensions";

/// A plugin that can have a page in the sidebar (H3e).
///
/// The frontend builds these from `plugin.list`; this model never talks to a
/// backend.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PluginNode {
    /// Catalogue id. A LOOKUP KEY: byte-exact, never masked (masking is not
    /// injective, so it would collapse two distinct plugins onto one row).
    pub id: String,
    /// `PluginInfo.name`, ALREADY masked and capped by the caller — this
    /// model does no masking, it only carries what the frontend prepared.
    pub title: String,
    /// The plugin ships a `help.md` (`PluginInfo.has_help`). Without one there
    /// is no page and therefore no row: a node that opens nothing is a dead
    /// end the reader pays for with a keystroke.
    pub has_help: bool,
    /// Approved AND enabled. It does not decide whether the page shows — a
    /// human reads a plugin's documentation precisely to decide whether to
    /// enable it — only whether its command rows are runnable.
    pub active: bool,
}

/// One row of the sidebar.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SidebarRow {
    /// Group header — the tag shared by the topics under it. NOT selectable.
    Group {
        /// The tag itself; the frontend translates it (`help-group-{tag}`).
        tag: String,
    },
    /// A topic the reader can open.
    Topic {
        /// Its id.
        id: TopicId,
        /// Its title, already the corpus' own (masked at parse for plugins).
        ///
        /// The one exception is the synthetic [`KEYS_ID`] entry, whose title
        /// is the label the frontend handed to [`HelpState::new`]: this
        /// module has no Fluent access on purpose. Painters can therefore
        /// print this field for EVERY row, with no special case, and the
        /// filter matches what is on screen.
        title: String,
    },
}

/// Which half of the overlay has the cursor.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Focus {
    /// The sidebar: up/down change the open topic.
    Topics,
    /// The body: up/down walk the runnable rows and links, Enter acts.
    Body,
}

/// What `Enter` does on the focused body row.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Action {
    /// Dispatch a command — the same id the palette sends.
    Run(String),
    /// Open another topic.
    Open(TopicId),
}

/// The overlay's whole state.
///
/// ```
/// use norte_frontend::help::{Focus, HelpState};
/// use norte_help::{Lang, TopicId};
///
/// // The label of the synthetic keyboard page comes from the frontend's own
/// // catalogue — this model never touches Fluent.
/// let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
/// assert_eq!(help.current().as_str(), "index");
/// assert_eq!(help.focus(), Focus::Topics);
///
/// // Following a link moves the body and remembers where the reader was.
/// help.open(&TopicId::new("copying"));
/// assert_eq!(help.current().as_str(), "copying");
/// assert!(help.back());
/// assert_eq!(help.current().as_str(), "index");
///
/// // A link the corpus cannot resolve is ignored, never a panic.
/// help.open(&TopicId::new("no-such-topic"));
/// assert_eq!(help.current().as_str(), "index");
/// ```
#[derive(Clone, Debug)]
pub struct HelpState {
    lang: Lang,
    /// Label of the synthetic [`KEYS_ID`] row, as the frontend paints it.
    keys_label: String,
    current: TopicId,
    history: Vec<TopicId>,
    rows: Vec<SidebarRow>,
    cursor: usize,
    filter: String,
    filtering: bool,
    focus: Focus,
    actions: Vec<Action>,
    action_cursor: usize,
    /// Focus has JUST arrived at the body and the action cursor has not
    /// moved yet (#help): while it is set, whoever paints must bring the
    /// cursor to what is ALREADY being read instead of dragging the view to
    /// wherever the cursor is.
    ///
    /// Without this, moving to the body would teleport you to the first
    /// executable line — which on a long page sits behind all the prose —
    /// so `Tab` did not look like it changed column: it looked like it
    /// jumped to the end.
    action_follows_view: bool,
    body_scroll: usize,
    /// Plugin nodes, in catalogue order, minus the ones dropped by
    /// [`HelpState::set_plugins`].
    plugins: Vec<PluginNode>,
    /// Pages already fetched, keyed by plugin id. Owned, because they are
    /// parsed at runtime — the corpus is `'static` and these are not.
    plugin_topics: BTreeMap<String, Topic>,
}

impl HelpState {
    /// Opens the overlay on the index topic of `lang`.
    ///
    /// `keys_label` is the title of the synthetic [`KEYS_ID`] row, already
    /// localized by the caller: this module has no Fluent access on purpose
    /// (the same page is named differently in the TUI and the GUI), so the
    /// label is data here like every corpus title, and the filter matches it
    /// like every corpus title. A blank label falls back to the id, which
    /// beats an empty sidebar row if a frontend ever forgets.
    ///
    /// See the type's own example: the constructor is where the reader lands,
    /// so its behaviour is documented there alongside what follows from it.
    #[must_use]
    pub fn new(lang: Lang, keys_label: String) -> Self {
        // The index is the entry point, but the corpus is data: if it ever
        // ships without one, opening on the first page beats opening on a
        // blank body that no key can leave.
        let current = topics(lang)
            .iter()
            .find(|t| t.id.as_str() == INDEX_ID)
            .or_else(|| topics(lang).first())
            .map_or_else(|| TopicId::new(KEYS_ID), |t| t.id.clone());
        let keys_label = if keys_label.trim().is_empty() {
            KEYS_ID.to_owned()
        } else {
            keys_label
        };
        let mut state = Self {
            lang,
            keys_label,
            current,
            history: Vec::new(),
            rows: Vec::new(),
            cursor: 0,
            filter: String::new(),
            filtering: false,
            focus: Focus::Topics,
            actions: Vec::new(),
            action_cursor: 0,
            action_follows_view: false,
            body_scroll: 0,
            plugins: Vec::new(),
            plugin_topics: BTreeMap::new(),
        };
        state.rebuild_rows();
        state.rebuild_actions();
        state
    }

    /// Id of the topic the body is showing.
    #[must_use]
    pub fn current(&self) -> &TopicId {
        &self.current
    }

    /// The corpus locale this overlay was opened on.
    ///
    /// A painter needs it to resolve an id BACK to the page it names — a
    /// `see_also` row is painted with the topic's title, the same string the
    /// sidebar shows — and the corpus is keyed by language, so the id alone is
    /// not enough.
    ///
    /// ```
    /// use norte_frontend::help::HelpState;
    /// use norte_help::Lang;
    ///
    /// let help = HelpState::new(Lang::Es, "Teclado".to_owned());
    /// assert_eq!(help.lang(), Lang::Es);
    /// ```
    #[must_use]
    pub fn lang(&self) -> Lang {
        self.lang
    }

    /// The open corpus topic, or `None` for the synthetic [`KEYS_ID`] page
    /// (whose body the frontend generates from the effective keymap) and for a
    /// plugin page, which is not `'static`.
    ///
    /// Prefer [`current_topic`](Self::current_topic): this one answers "is the
    /// open page a corpus page", which only a caller that genuinely needs the
    /// `'static` lifetime should be asking.
    #[must_use]
    pub fn topic(&self) -> Option<&'static Topic> {
        norte_help::topic(self.lang, self.current.as_str())
    }

    /// Installs the plugin nodes the sidebar offers (H3e).
    ///
    /// Three kinds are DROPPED, and every drop is deliberate:
    ///
    /// * a plugin with no `help.md` — its node would open nothing;
    /// * a repeated id, FIRST-WINS — catalogue order is the order the
    ///   extension manager and the palette already show, so the first node is
    ///   the one the reader has seen elsewhere. `Catalog::load_dir` rejects a
    ///   duplicate id fail-closed and a locally-discovered catalogue cannot
    ///   produce one, but these nodes are built from `plugin.list`, which
    ///   crosses the wire, and this model does not get to assume the peer
    ///   enforced what our host enforces;
    /// * a plugin whose id is also a corpus topic id (or the synthetic keys
    ///   page). `parse_untrusted` assigns the topic the host-supplied id, so a
    ///   plugin published as `copying` would otherwise sit in the same id space
    ///   as the built-in page of that name and every `[[copying]]` in the
    ///   corpus could land in third-party prose. The corpus wins; `norte
    ///   doctor` reports the collision so the loss is not silent.
    ///
    ///   That collision cannot arise TODAY from a locally-discovered plugin:
    ///   `norte_plugin_host::manifest::is_valid_plugin_id` demands reverse-DNS
    ///   (two dot-separated segments) and every corpus id is a single segment,
    ///   so a manifest saying `id = "copying"` does not load at all. The guard
    ///   stays because the ids reaching this method came off the WIRE and the
    ///   id space belongs to another crate, which promises this one nothing.
    ///   [`current_topic`](Self::current_topic)'s lookup order is the second
    ///   half of the same defence.
    ///
    /// Any page already fetched for a plugin that is no longer in the list is
    /// forgotten with it — the catalogue is the truth about what exists.
    pub fn set_plugins(&mut self, nodes: Vec<PluginNode>) {
        let mut seen: BTreeSet<String> = BTreeSet::new();
        self.plugins = nodes
            .into_iter()
            .filter(|n| n.has_help)
            .filter(|n| n.id != KEYS_ID && norte_help::topic(self.lang, &n.id).is_none())
            .filter(|n| seen.insert(n.id.clone()))
            .collect();
        self.plugin_topics
            .retain(|id, _| self.plugins.iter().any(|n| &n.id == id));
        self.rebuild_rows();
        // The open page may have just stopped existing (a plugin left the
        // catalogue while the reader was on it). `rebuild_rows` ends by moving
        // the body onto the row the cursor landed on — that is its own TAIL
        // block, not `sync_cursor`, which moves only the cursor — so wherever
        // the sidebar still has a row, `current` follows it and the actions of
        // the page that replaced it are rebuilt here.
        //
        // The one case that does NOT recover is a sidebar left EMPTY by a
        // filter: there is nowhere to follow to, and `rebuild_rows`
        // deliberately keeps showing what was being read (see its tail and
        // `a_filter_that_matches_nothing_leaves_the_open_topic_alone`). Then
        // `current` names a plugin that is gone, and BOTH `current_topic` and
        // `plugin_needs_fetch` answer `None` — so a frontend that told the
        // synthetic keyboard page apart by "no topic resolved" would paint the
        // whole cheatsheet under that plugin's name.
        //
        // Not papered over here, for two reasons. It is unreachable from the
        // shipped callers — the catalogue is installed on the OPEN path, before
        // a filter has been typed or a page opened — and the filter behaviour it
        // would collide with is a deliberate decision, not an oversight. What
        // the frontends owe instead is to branch on the ID
        // (`norte_tui::app::HelpView::refresh` keys its keyboard-page arm on
        // `KEYS_ID`), which is correct no matter how `current` got stale. A
        // caller that ever refreshes the catalogue MID-overlay has to decide
        // what a vanished page should show, and that decision belongs with it.
        self.rebuild_actions();
    }

    /// Installs a page parsed from `plugin.help` (H3e). Ignored when the
    /// plugin is not a current node — a late answer for a plugin that has
    /// since left the catalogue must not resurrect it.
    pub fn install_plugin_topic(&mut self, topic: Topic) {
        let Origin::Plugin { id, .. } = &topic.origin else {
            return;
        };
        if !self.plugins.iter().any(|n| &n.id == id) {
            return;
        }
        self.plugin_topics.insert(id.clone(), topic);
        self.rebuild_actions();
    }

    /// The open page, whatever it is: the corpus FIRST, then a plugin's. The
    /// order is the shadowing guard's second half — even if a node slipped
    /// past [`set_plugins`](Self::set_plugins), the built-in page would still
    /// win here.
    ///
    /// `None` for the synthetic keyboard page, and for a plugin node whose
    /// page has not arrived yet (see
    /// [`plugin_needs_fetch`](Self::plugin_needs_fetch)).
    #[must_use]
    pub fn current_topic(&self) -> Option<&Topic> {
        norte_help::topic(self.lang, self.current.as_str())
            .or_else(|| self.plugin_topics.get(self.current.as_str()))
    }

    /// The plugin id whose page the reader is on and the state does not have
    /// yet — what the frontend must ask `plugin.help` for. `None` when the
    /// open page is a corpus page, the keyboard page, or an already-fetched
    /// plugin page.
    #[must_use]
    pub fn plugin_needs_fetch(&self) -> Option<&str> {
        let id = self.current.as_str();
        (norte_help::topic(self.lang, id).is_none()
            && !self.plugin_topics.contains_key(id)
            && self.plugins.iter().any(|n| n.id == id))
        .then_some(id)
    }

    /// Whether the plugin owning the open page is active (approved AND
    /// enabled). `true` for anything that is not a plugin page: a corpus page
    /// has no plugin to be inactive.
    #[must_use]
    pub fn current_plugin_active(&self) -> bool {
        self.plugins
            .iter()
            .find(|n| n.id == self.current.as_str())
            .is_none_or(|n| n.active)
    }

    /// The sidebar as it stands under the current filter.
    #[must_use]
    pub fn rows(&self) -> &[SidebarRow] {
        &self.rows
    }

    /// Index into [`rows`](Self::rows) of the selected row. Always a
    /// [`SidebarRow::Topic`] while the sidebar has one.
    #[must_use]
    pub fn cursor(&self) -> usize {
        self.cursor
    }

    /// Which half of the overlay the cursor keys drive.
    #[must_use]
    pub fn focus(&self) -> Focus {
        self.focus
    }

    /// Everything the open topic offers: its commands, then its `see_also`.
    #[must_use]
    pub fn actions(&self) -> &[Action] {
        &self.actions
    }

    /// The action `Enter` would take, or `None` when the body does not hold
    /// the focus (the sidebar's `Enter` opens a topic, it does not run
    /// anything).
    #[must_use]
    pub fn action(&self) -> Option<&Action> {
        match self.focus {
            Focus::Body => self.actions.get(self.action_cursor),
            Focus::Topics => None,
        }
    }

    /// Index into [`actions`](Self::actions) of the focused body row.
    #[must_use]
    pub fn action_cursor(&self) -> usize {
        self.action_cursor
    }

    /// First body line the renderer should paint.
    #[must_use]
    pub fn body_scroll(&self) -> usize {
        self.body_scroll
    }

    /// Scrolls the body so that `line` sits inside a window of `height`
    /// lines, moving as little as possible.
    ///
    /// The height arrives from the caller because the renderer is the only
    /// side that knows it: this model has no idea how tall a terminal row or
    /// a GPUI line is, and guessing would make the two frontends scroll
    /// differently over the same topic. A `height` of zero is a no-op — there
    /// is no window to reveal anything in.
    ///
    /// Every step saturates. Both numbers come from a laid-out body, and
    /// arithmetic that only holds for plausible bodies is arithmetic that
    /// aborts the process the day one is not.
    pub fn reveal(&mut self, line: usize, height: usize) {
        if height == 0 {
            return;
        }
        if line < self.body_scroll {
            self.body_scroll = line;
        } else if line >= self.body_scroll.saturating_add(height) {
            // `line - (height - 1)`, ordered so that neither end can wrap and
            // the answer stays exact right up to `usize::MAX` (adding first
            // would saturate the +1 away and lose a line).
            self.body_scroll = line.saturating_sub(height.saturating_sub(1));
        }
    }

    /// Clamps the scroll to a body of `total` lines.
    ///
    /// The renderer calls this once per frame with the line count it just
    /// laid out. The count cannot live in this model — it depends on the
    /// width the prose was wrapped to, which is the one thing a render-
    /// agnostic model does not know — so [`page_down`](Self::page_down)
    /// deliberately does not bound itself and this is where the bound
    /// arrives, exactly as `height` arrives in [`reveal`](Self::reveal).
    /// Same idiom as the viewer's `total_rows` clamp.
    pub fn clamp_scroll(&mut self, total: usize) {
        self.body_scroll = self.body_scroll.min(total.saturating_sub(1));
    }

    /// Clamps the scroll so that the LAST screen is a full one: the body
    /// never scrolls past `total - height`.
    ///
    /// The sibling of [`clamp_scroll`](Self::clamp_scroll) for a renderer
    /// that knows its window as well as its line count. Clamping to the last
    /// LINE lets a reader page on until one line of text sits over a box of
    /// blank rows, and it is what makes [`bottom`](Self::bottom) land on the
    /// end of the page rather than past it.
    pub fn clamp_scroll_window(&mut self, total: usize, height: usize) {
        self.body_scroll = self.body_scroll.min(total.saturating_sub(height));
    }

    /// The first page of the sidebar, or the top of the body — `Home`.
    ///
    /// In the body it moves the SCROLL, like [`page_up`](Self::page_up): going
    /// to the top of a page is reading it, not choosing one of its rows.
    pub fn top(&mut self) {
        self.action_follows_view = true;
        match self.focus {
            Focus::Topics => self.move_sidebar(false, self.rows.len()),
            Focus::Body => self.body_scroll = 0,
        }
    }

    /// The last page of the sidebar, or the end of the body — `End`.
    ///
    /// The body end is unbounded here and bounded by the painter
    /// ([`clamp_scroll_window`](Self::clamp_scroll_window)), for the reason
    /// [`clamp_scroll`](Self::clamp_scroll) gives: only the renderer knows how
    /// many lines the page wrapped into.
    pub fn bottom(&mut self) {
        self.action_follows_view = true;
        match self.focus {
            Focus::Topics => self.move_sidebar(true, self.rows.len()),
            Focus::Body => self.body_scroll = usize::MAX,
        }
    }

    /// Whether typed characters are going into the filter.
    #[must_use]
    pub fn filtering(&self) -> bool {
        self.filtering
    }

    /// The filter as typed: RAW, for MATCHING — and public because task 7
    /// hands it to the command palette, which matches on it too.
    ///
    /// `raw` is in the name on purpose. The one that may be painted is
    /// [`filter_display`](Self::filter_display); a bare `filter()` sitting
    /// next to a masked sibling is a trap for whoever writes the second
    /// frontend, and the cost of falling into it is a `U+202E` echoed into a
    /// terminal.
    #[must_use]
    pub fn filter_raw(&self) -> &str {
        &self.filter
    }

    /// The filter with terminal hazards masked, for painting.
    ///
    /// Matching and painting deliberately see different text: a needle
    /// carrying a bidi override must still find the topic the reader means
    /// (the corpus is folded raw too), but a `U+202E` echoed back into a
    /// terminal reorders the line it lands in.
    #[must_use]
    pub fn filter_display(&self) -> String {
        mask_terminal_hazards(&self.filter)
    }

    /// Routes typed characters into the filter, and hands the cursor back to
    /// the sidebar.
    ///
    /// Filtering is a SIDEBAR gesture: what the box narrows is the list of
    /// topics, and the arrow keys inside it are there to walk the hits. Left
    /// with the focus in the body they walked the ACTION cursor of the page
    /// underneath instead, and the list being filtered — the only thing on
    /// screen that had just changed — could not be walked at all. An invariant
    /// of the type rather than of each caller, on the same grounds as
    /// [`push_char`](Self::push_char)'s `filtering` guard.
    pub fn start_filter(&mut self) {
        self.filtering = true;
        self.focus = Focus::Topics;
    }

    /// Stops routing typed characters into the filter, KEEPING the text:
    /// `Esc` leaves the search box, it does not undo the search. Emptying it
    /// is what [`backspace`](Self::backspace) is for.
    pub fn end_filter(&mut self) {
        self.filtering = false;
    }

    /// Appends a character to the filter and rebuilds the sidebar. No-op
    /// unless [`filtering`](Self::filtering) — the caller already branches on
    /// that, but the guard here makes it an invariant OF THE TYPE and not of
    /// each of the three call sites (same criterion as `settings.rs`).
    pub fn push_char(&mut self, c: char) {
        if !self.filtering {
            return;
        }
        self.filter.push(c);
        self.rebuild_rows();
    }

    /// Drops the last character of the filter and rebuilds the sidebar. No-op
    /// while not [`filtering`](Self::filtering), like
    /// [`push_char`](Self::push_char).
    pub fn backspace(&mut self) {
        if !self.filtering {
            return;
        }
        self.filter.pop();
        self.rebuild_rows();
    }

    /// Opens `id`, remembering the current topic so [`back`](Self::back) can
    /// return to it.
    ///
    /// An id that resolves to nothing — a `see_also` or a `[[link]]` pointing
    /// at a page this locale's corpus does not have — is IGNORED: no history
    /// entry, no change of body, no panic. A dangling link in the prose is a
    /// corpus defect (`norte_help::check_corpus` catches it), and the reader
    /// pressing Enter on it is not the person who should find out.
    ///
    /// This is the NAVIGATING verb, and the only one that touches the
    /// history: a `[[link]]`, an [`Action::Open`], Enter on the sidebar.
    /// Merely arrowing the sidebar previews instead (see
    /// [`down`](Self::down)) — otherwise every keystroke of a scan through
    /// the index would owe the reader one press of `Esc` before the overlay
    /// could close.
    pub fn open(&mut self, id: &TopicId) {
        let previous = self.current.clone();
        self.show(id);
        if self.current != previous {
            self.history.push(previous);
        }
    }

    /// Shows `id` as the ROOT of the reader's trail: the body changes and the
    /// history is left EMPTY, so [`back`](Self::back) answers `false`.
    ///
    /// The verb for a page the reader did not navigate to but was PUT on —
    /// contextual help (`F1` over a dialog opens the page about that dialog).
    /// [`open`](Self::open) would be wrong there twice over: the reader never
    /// visited the index, so "back to the index" is a place they never were,
    /// and the frontends make `back` at the root mean CLOSE. One press of
    /// `Esc` has to leave a page nobody asked to be on.
    ///
    /// An unknown id changes nothing (as in `open`), but the history is
    /// cleared either way: the caller is stating where the trail STARTS, and
    /// that is true whether or not this locale's corpus has the page.
    ///
    /// ```
    /// use norte_frontend::help::HelpState;
    /// use norte_help::{Lang, TopicId};
    ///
    /// let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
    /// help.open(&TopicId::new("copying"));
    /// help.open_as_root(&TopicId::new("archives"));
    /// assert_eq!(help.current().as_str(), "archives");
    /// assert!(!help.back(), "nothing to walk back to");
    /// ```
    pub fn open_as_root(&mut self, id: &TopicId) {
        self.show(id);
        self.history.clear();
    }

    /// Whether [`back`](Self::back) would go anywhere.
    ///
    /// Asking WITHOUT walking, which the mutating verb cannot answer: a
    /// renderer paints `⌫ back` or `⌫ close` from this, and a surface that
    /// had to call `back` to find out would have already left the page.
    ///
    /// ```
    /// use norte_frontend::help::HelpState;
    /// use norte_help::{Lang, TopicId};
    ///
    /// let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
    /// assert!(!help.can_back(), "the root has nowhere to go back to");
    /// help.open(&TopicId::new("copying"));
    /// assert!(help.can_back());
    /// ```
    #[must_use]
    pub fn can_back(&self) -> bool {
        !self.history.is_empty()
    }

    /// Goes back to the previously open topic. `false` when there is no
    /// history left, so the caller can decide what `Esc`/`Backspace` means
    /// then (the TUI closes the overlay).
    #[must_use]
    pub fn back(&mut self) -> bool {
        let Some(previous) = self.history.pop() else {
            return false;
        };
        self.current = previous;
        self.after_open();
        true
    }

    /// Moves the cursor one row up: one topic in the sidebar, one action in
    /// the body.
    pub fn up(&mut self) {
        self.action_follows_view = false;
        match self.focus {
            Focus::Topics => self.move_sidebar(false, 1),
            Focus::Body => self.action_cursor = self.action_cursor.saturating_sub(1),
        }
    }

    /// Moves the cursor one row down: one topic in the sidebar, one action in
    /// the body.
    pub fn down(&mut self) {
        self.action_follows_view = false;
        match self.focus {
            Focus::Topics => self.move_sidebar(true, 1),
            Focus::Body => self.clamp_action(self.action_cursor.saturating_add(1)),
        }
    }

    /// Moves `n` topics up in the sidebar, or scrolls the body `n` lines up.
    ///
    /// Paging the body moves the SCROLL and not the action cursor: a page is
    /// a movement over prose, and most of a topic is prose with no action on
    /// it at all.
    /// **Who calls this, by surface** (#267): the TUI, on both halves,
    /// because it paints on a grid and has no scroll to delegate to. The
    /// graphical window ONLY on the sidebar: a page's body crosses its
    /// whole bridge and the DOM scrolls it, so moving `body_scroll` here
    /// would create a second truth about where the help is, and only one
    /// of the two would get painted. A third renderer with no native scroll
    /// uses both halves, like the TUI.
    pub fn page_up(&mut self, n: usize) {
        // Paging is reading, not choosing: the view governs and the cursor
        // stays wherever the reader leaves it once they move it again.
        self.action_follows_view = true;
        match self.focus {
            Focus::Topics => self.move_sidebar(false, n),
            Focus::Body => self.body_scroll = self.body_scroll.saturating_sub(n),
        }
    }

    /// Moves `n` topics down in the sidebar, or scrolls the body `n` lines
    /// down. See [`page_up`](Self::page_up).
    pub fn page_down(&mut self, n: usize) {
        self.action_follows_view = true;
        match self.focus {
            Focus::Topics => self.move_sidebar(true, n),
            Focus::Body => self.body_scroll = self.body_scroll.saturating_add(n),
        }
    }

    /// Puts the sidebar cursor on ROW `row` and shows what it lands on — what
    /// a CLICK on that row means.
    ///
    /// The same landing the arrow keys perform (`show`, not `open`): moving
    /// the cursor over the sidebar is reading it, and it does not push a step
    /// onto the trail that `Backspace` would then have to walk back. Clicking
    /// a row the reader can already see should not behave differently from
    /// arrowing onto it.
    ///
    /// A GROUP header and an out-of-range index are both no-ops: a header is
    /// not a page, and the caller is a painter that may be one frame behind
    /// the model. The focus moves to the sidebar, because the click says where
    /// the reader is now looking.
    pub fn click_row(&mut self, row: usize) {
        if !matches!(self.rows.get(row), Some(SidebarRow::Topic { .. })) {
            return;
        }
        self.focus = Focus::Topics;
        self.cursor = row;
        if let Some(landed) = self.selected_topic().cloned() {
            self.show(&landed);
        }
    }

    /// Puts the body cursor on action `i` — what a CLICK on a runnable row or
    /// a link means, one half of it.
    ///
    /// Only moves the cursor; the caller decides whether the click also RUNS
    /// it, because running is what needs the frozen resolver's verdict and a
    /// dispatch path this model knows nothing about. Out of range is a no-op,
    /// for the same reason [`click_row`](Self::click_row) tolerates it.
    ///
    /// The focus moves to the body: the next arrow key belongs where the
    /// reader just pointed.
    pub fn click_action(&mut self, i: usize) {
        if i >= self.actions.len() {
            return;
        }
        self.focus = Focus::Body;
        self.action_cursor = i;
    }

    /// Puts the body's first visible line AT `line` — dragging a scrollbar.
    ///
    /// Absolute where [`scroll_body`](Self::scroll_body) is relative, because a
    /// drag says "show me THIS part of the page" and a wheel says "a bit
    /// further". The far end is clamped by
    /// [`clamp_scroll`](Self::clamp_scroll) once the painter knows how many
    /// lines there are.
    pub fn scroll_body_to(&mut self, line: usize) {
        self.action_follows_view = true;
        self.body_scroll = line;
    }

    /// Scrolls the body by `lines`, negative up — the wheel.
    ///
    /// Unlike [`page_up`](Self::page_up) it does NOT depend on the focus: the
    /// wheel scrolls what the pointer is over, which is the rule the panes
    /// already follow (`mouse`'s own help page says so). Saturating at zero;
    /// the far end is clamped by [`clamp_scroll`](Self::clamp_scroll) once the
    /// painter knows how many lines there are.
    ///
    /// Like paging, it hands the lead to the VIEW: with the action cursor
    /// leading, the painter would reveal the cursor's line again on the next
    /// frame and undo the turn of the wheel.
    pub fn scroll_body(&mut self, lines: isize) {
        self.action_follows_view = true;
        self.body_scroll = if lines < 0 {
            self.body_scroll.saturating_sub(lines.unsigned_abs())
        } else {
            self.body_scroll.saturating_add(lines.unsigned_abs())
        };
    }

    /// Hands the focus to the other half.
    ///
    /// A body with nothing runnable on it (the keyboard page, a topic with
    /// neither commands nor `see_also`) takes the focus too. It used to
    /// refuse, on the grounds that the arrow keys could not move it — but the
    /// page keys CAN, and with the focus refused they walked the sidebar, so
    /// the keyboard page, the longest one, could not be read past its first
    /// screen. In the body the arrows scroll the text when no action is in
    /// view, so the focus there is never a dead end.
    pub fn toggle_focus(&mut self) {
        self.focus = match self.focus {
            Focus::Body => Focus::Topics,
            Focus::Topics => {
                // The cursor goes to where the reader is, not the other way
                // around.
                self.action_follows_view = true;
                Focus::Body
            }
        };
    }

    /// Does the action cursor have to be brought to the current view,
    /// instead of dragging the view to the cursor? See
    /// [`Self::action_follows_view`] in the struct: [`Self::toggle_focus`]
    /// arms it and the reader's first move disarms it.
    #[must_use]
    pub fn action_follows_view(&self) -> bool {
        self.action_follows_view
    }

    /// Puts the action cursor at `i` WITHOUT the view chasing it: this is
    /// what the painter does once focus has just arrived at the body and it
    /// already knows which actions fall inside the window.
    pub fn settle_action_cursor(&mut self, i: usize) {
        self.clamp_action(i);
        self.action_follows_view = false;
    }

    /// Id under the sidebar cursor, or `None` when the filter left the
    /// sidebar empty.
    #[must_use]
    pub fn selected_topic(&self) -> Option<&TopicId> {
        match self.rows.get(self.cursor) {
            Some(SidebarRow::Topic { id, .. }) => Some(id),
            Some(SidebarRow::Group { .. }) | None => None,
        }
    }

    /// Opens whatever the sidebar cursor is on.
    pub fn open_selected(&mut self) {
        if let Some(id) = self.selected_topic().cloned() {
            self.open(&id);
        }
    }

    /// Whether `id` names something this overlay can show.
    ///
    /// A plugin NODE counts, page in hand or not: its body may still be in
    /// flight (see [`plugin_needs_fetch`](Self::plugin_needs_fetch)), and a
    /// reader who cannot open the row they can see would have to press the key
    /// twice to find out the answer arrived. The catalogue, not the cache, is
    /// what says the page exists — which is also why a plugin that LEFT the
    /// catalogue stops being openable even with its page still parsed.
    fn exists(&self, id: &TopicId) -> bool {
        id.as_str() == KEYS_ID
            || norte_help::topic(self.lang, id.as_str()).is_some()
            || self.plugins.iter().any(|n| n.id == id.as_str())
    }

    /// Shows `id` WITHOUT remembering where the reader was.
    ///
    /// The half of [`open`](Self::open) that changes the body. Previewing
    /// (arrowing the sidebar) and re-syncing after a filter both change what
    /// is on screen without being a place the reader chose to go, so neither
    /// of them may leave a step behind for `back()` to walk.
    ///
    /// An unknown id is ignored, and so is the id already open — the second
    /// guard is what keeps `open` from stacking a topic on top of itself.
    fn show(&mut self, id: &TopicId) {
        if *id == self.current || !self.exists(id) {
            return;
        }
        self.current = id.clone();
        self.after_open();
    }

    /// Common tail of [`open`](Self::open) and [`back`](Self::back): the body
    /// changed, so its actions, its scroll and the sidebar cursor follow it.
    fn after_open(&mut self) {
        self.body_scroll = 0;
        self.rebuild_actions();
        self.sync_cursor();
    }

    /// Rebuilds the sidebar from the corpus and the current filter.
    ///
    /// Corpus order, never alphabetical — the corpus is written in reading
    /// order and `norte_help::topic_ids` pins the same order in every locale.
    /// A header is emitted whenever the first tag CHANGES, so a tag that the
    /// corpus splits into two runs gets two headers: that is the table of
    /// contents the author wrote, and silently regrouping it would reorder
    /// the reading path.
    fn rebuild_rows(&mut self) {
        let needle = fold_for_search(&self.filter);
        // Two tiers (see `matches`): a page's text only counts when none of
        // them is named that or documents a command that is.
        let by_text = !needle.is_empty() && !topics(self.lang).iter().any(|t| matches(t, &needle));
        let mut rows: Vec<SidebarRow> = Vec::new();
        let mut group: Option<&str> = None;
        for topic in topics(self.lang) {
            let matched = if by_text {
                matches_text(topic, &needle)
            } else {
                matches(topic, &needle)
            };
            if !matched {
                continue;
            }
            let tag = topic.tags.first().map_or("", String::as_str);
            if group != Some(tag) {
                // An untagged topic gets NO header: the tag is a Fluent key
                // stem (`help-group-{tag}`), and an empty one would send the
                // frontend looking up `help-group-`, which resolves to
                // nothing and paints as a stray blank band.
                if !tag.is_empty() {
                    rows.push(SidebarRow::Group {
                        tag: tag.to_owned(),
                    });
                }
                group = Some(tag);
            }
            rows.push(SidebarRow::Topic {
                id: topic.id.clone(),
                title: topic.title.clone(),
            });
        }
        // Same rule as [`matches`] applies to the corpus: id OR title. The
        // title here is the frontend's own label, so a reader who types what
        // the row SAYS (`tecl…` against `Teclado`) finds the row they are
        // looking straight at — before, only the literal `keys` reached it.
        if needle.is_empty()
            || fold_for_search(KEYS_ID).contains(&needle)
            || fold_for_search(&self.keys_label).contains(&needle)
        {
            rows.push(SidebarRow::Group {
                tag: KEYS_TAG.to_owned(),
            });
            rows.push(SidebarRow::Topic {
                id: TopicId::new(KEYS_ID),
                title: self.keys_label.clone(),
            });
        }
        // The plugin pages go LAST, under their own header: they are the only
        // rows the host did not write, and the reading order the corpus author
        // laid out ends where third-party prose begins. Catalogue order within
        // the group, for the same reason the corpus keeps corpus order.
        //
        // Filtered by id OR title like every other row — the title being the
        // already-masked name the frontend handed in, so the reader finds the
        // row by what it SAYS. Nothing to match on beyond those two: a node is
        // not a topic, and its commands are only known once its page arrives.
        let hits: Vec<&PluginNode> = self
            .plugins
            .iter()
            .filter(|n| {
                needle.is_empty()
                    || fold_for_search(&n.id).contains(&needle)
                    || fold_for_search(&n.title).contains(&needle)
            })
            .collect();
        if !hits.is_empty() {
            rows.push(SidebarRow::Group {
                tag: PLUGINS_TAG.to_owned(),
            });
            rows.extend(hits.into_iter().map(|n| SidebarRow::Topic {
                id: TopicId::new(&n.id),
                title: n.title.clone(),
            }));
        }
        self.rows = rows;
        self.sync_cursor();

        // The highlight and the body are ONE thing. When the filter hides the
        // open topic the cursor lands on the first survivor, and the body has
        // to follow it there — otherwise the sidebar highlights `mouse` over
        // a body still showing `index`, and the next arrow key steps away
        // from a row the reader never saw opened. Not history: the reader
        // typed a letter, they did not choose to go anywhere.
        //
        // When NOTHING survived there is nowhere to follow to, and the body
        // keeps showing what was being read.
        //
        // The reverse direction is deliberately NOT symmetric: opening a
        // topic the current filter hides (a `see_also` link out of a filtered
        // list) keeps the body on the topic the reader chose and leaves the
        // highlight on the nearest visible row — there is no row to move it
        // to. A renderer that wants to say so compares `selected_topic()`
        // with `current()`.
        if self.row_of(&self.current).is_none()
            && let Some(landed) = self.selected_topic().cloned()
        {
            self.show(&landed);
        }
    }

    /// Puts the cursor back on the open topic, or on the first selectable row
    /// when the filter hid it. Never on a header, never out of bounds.
    fn sync_cursor(&mut self) {
        self.cursor = self
            .row_of(&self.current)
            .or_else(|| self.next_topic_row(0, true, true))
            .unwrap_or(0);
        debug_assert!(
            self.rows.is_empty()
                || matches!(self.rows.get(self.cursor), Some(SidebarRow::Topic { .. })),
            "the cursor must sit on a selectable row: {} of {:?}",
            self.cursor,
            self.rows
        );
    }

    /// Index of `id`'s row, if the sidebar is showing it.
    fn row_of(&self, id: &TopicId) -> Option<usize> {
        self.rows.iter().position(|row| match row {
            SidebarRow::Topic { id: row_id, .. } => row_id == id,
            SidebarRow::Group { .. } => false,
        })
    }

    /// Next selectable row from `from` in the given direction, skipping group
    /// headers. `inclusive` also considers `from` itself, which is what makes
    /// this usable both to step (exclusive) and to land (inclusive).
    /// `None` at the ends: the sidebar does NOT wrap.
    fn next_topic_row(&self, from: usize, forward: bool, inclusive: bool) -> Option<usize> {
        let mut i = from;
        if !inclusive {
            i = if forward {
                i.checked_add(1)?
            } else {
                i.checked_sub(1)?
            };
        }
        loop {
            match self.rows.get(i) {
                Some(SidebarRow::Topic { .. }) => return Some(i),
                Some(SidebarRow::Group { .. }) => {
                    i = if forward {
                        i.checked_add(1)?
                    } else {
                        i.checked_sub(1)?
                    };
                }
                None => return None,
            }
        }
    }

    /// Moves the sidebar cursor `n` selectable rows, stopping at the ends.
    ///
    /// The cursor SHOWS what it lands on (preview semantics, the same as the
    /// theme picker): arrowing through the index has to show each page, not
    /// make the reader press Enter on every line to find out what it is. It
    /// shows and does not [`open`](Self::open) — a preview leaves no step in
    /// the history, see [`show`](Self::show).
    fn move_sidebar(&mut self, forward: bool, n: usize) {
        let mut cursor = self.cursor;
        for _ in 0..n {
            match self.next_topic_row(cursor, forward, false) {
                Some(next) => cursor = next,
                None => break,
            }
        }
        self.cursor = cursor;
        if let Some(landed) = self.selected_topic().cloned() {
            self.show(&landed);
        }
    }

    /// Puts the body cursor on `wanted`, clamped to the last action.
    fn clamp_action(&mut self, wanted: usize) {
        self.action_cursor = wanted.min(self.actions.len().saturating_sub(1));
    }

    /// Rebuilds what `Enter` can do on the open topic: its commands in
    /// declared order, then its `see_also` links. Empty for the keyboard page
    /// — its rows are chords, and a chord is not something you press Enter on
    /// — and for a plugin page that has not arrived yet.
    ///
    /// A plugin page contributes its own commands (`parse_untrusted` accepts
    /// only that plugin's own dispatch keys) and never any link: the parser
    /// drops `see_also`, so the links half is naturally empty.
    fn rebuild_actions(&mut self) {
        self.actions = self.current_topic().map_or_else(Vec::new, |topic| {
            topic
                .commands
                .iter()
                .cloned()
                .map(Action::Run)
                // `links()`: the `see_also` and AFTER it the prose's own
                // `[[links]]`, which used to be painted as a link and could
                // not be followed with either Enter or a click.
                .chain(topic.links().into_iter().map(Action::Open))
                .collect()
        });
        self.action_cursor = 0;
        if self.actions.is_empty() {
            self.focus = Focus::Topics;
        }
    }
}

/// Whether `topic` survives the (already folded) `needle`.
///
/// Id and title match by substring, like the palette and the quick search.
/// A command matches by PREFIX, deliberately: command ids are dotted keys,
/// and a substring rule makes `copy` drag in every page that merely mentions
/// `pane.copy` in passing — `mouse` documents it for ctrl-click — so the page
/// actually named "copying" arrives buried among them. Typing the key
/// (`pane.co`, `task.cancel`) still finds the page that documents it, which
/// is what matching commands at all was for.
///
/// The TEXT of the page is the second tier, [`matches_text`]: used only when
/// no page matches here. A word that is nobody's name (`bucket`)
/// still finds the page that explains it, and a word that IS a name keeps its
/// precise answer — searched in the prose, `copy` hit 15 of 23 pages and
/// buried «Copying» among them.
///
/// # Diacritics
///
/// Matched with [`fold_for_search`], not with the filename
/// [`crate::nav::fold`]: `raton` finds «ratón». The two had to split. That
/// one is shared with the filename path
/// (quick search, `nav`), where a name is BYTES and `café` and `cafe` are two
/// different files that must stay two rows; the help is prose, where they are
/// the same word typed in a hurry.
fn matches(topic: &Topic, needle: &str) -> bool {
    if needle.is_empty() {
        return true;
    }
    fold_for_search(topic.id.as_str()).contains(needle)
        || fold_for_search(&topic.title).contains(needle)
        || topic.commands.iter().any(|c| command_matches(c, needle))
}

/// The second tier of [`matches`]: the needle appears in the page's prose.
fn matches_text(topic: &Topic, needle: &str) -> bool {
    fold_for_search(&prose_of(topic)).contains(needle)
}

/// Folds help text for SEARCHING: canonical decomposition, combining marks
/// dropped, lower case. `Ratón` and `raton` fold to the same thing.
///
/// Help only — see [`matches`] for why the filename [`crate::nav::fold`] must
/// not do this.
fn fold_for_search(s: &str) -> String {
    use unicode_normalization::UnicodeNormalization as _;
    s.nfd()
        .filter(|c| !unicode_normalization::char::is_combining_mark(*c))
        .flat_map(char::to_lowercase)
        .collect()
}

/// The searchable text of a page: the prose of every block, one line each.
/// Command marks and links are left out — a command is matched by its id
/// ([`command_matches`]) and a link names ANOTHER page.
fn prose_of(topic: &Topic) -> String {
    use norte_help::{Block, Span};
    fn spans(out: &mut String, ss: &[Span]) {
        for s in ss {
            match s {
                Span::Text(t) | Span::Strong(t) | Span::Emph(t) | Span::Code(t) => {
                    out.push_str(t);
                }
                Span::CommandRef(_) | Span::TopicLink(_) => out.push(' '),
            }
        }
        out.push('\n');
    }
    let mut out = String::new();
    for b in &topic.blocks {
        match b {
            Block::Heading { text, .. } | Block::Code { text, .. } => {
                out.push_str(text);
                out.push('\n');
            }
            Block::Paragraph(ss) | Block::Callout { spans: ss, .. } => spans(&mut out, ss),
            Block::Bullets(items) => items.iter().for_each(|ss| spans(&mut out, ss)),
            Block::Table { header, rows } => {
                for cell in header.iter().chain(rows.iter().flatten()) {
                    out.push_str(cell);
                    out.push(' ');
                }
                out.push('\n');
            }
        }
    }
    out
}

/// A command matches when the needle is a prefix of its full id or of any of
/// its dot-separated SEGMENTS.
///
/// Segment-aware and not a plain `contains`, for the reason the palette's key
/// and text are kept apart: `co` should find `pane.copy`, and a reader who
/// types `copy` is looking for the copy key, not for every id with those four
/// letters somewhere inside. Prefix-only over the WHOLE id would be worse than
/// either — nobody types `pane.` before the verb, so the command half of the
/// filter would never fire for the word people actually search for.
///
/// A page that documents a command therefore surfaces for it, even when the
/// word is nowhere in its prose: searching `copy` finds the mouse page,
/// because dragging between panes IS a copy and that page is where it is
/// explained.
fn command_matches(command: &str, needle: &str) -> bool {
    let folded = fold_for_search(command);
    folded.starts_with(needle) || folded.split('.').any(|segment| segment.starts_with(needle))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::nav::fold;
    use norte_help::{Lang, TopicId};

    /// The label the TUI would hand in, standing in for `t("help-topic-keys")`
    /// — deliberately NOT the id, so a test that passes by matching `keys`
    /// cannot pass by accident.
    const KEYS_LABEL: &str = "Keyboard";

    fn state() -> HelpState {
        HelpState::new(Lang::En, KEYS_LABEL.to_owned())
    }

    /// A CLICK on a sidebar row lands where the arrow would have landed: it
    /// shows the page and does NOT push a step onto the trail (`Backspace`
    /// from there still closes, it does not undo the click).
    #[test]
    fn a_click_on_the_sidebar_lands_like_the_arrow() {
        let mut s = state();
        let row = s
            .rows()
            .iter()
            .position(|r| matches!(r, SidebarRow::Topic { id, .. } if id.as_str() == "copying"))
            .expect("`copying` is on the sidebar");
        s.click_row(row);
        assert_eq!(s.cursor(), row);
        assert_eq!(s.current().as_str(), "copying");
        assert_eq!(s.focus(), Focus::Topics);
        assert!(
            !s.back(),
            "landing is not navigating: there is no step to undo"
        );
    }

    /// A click on a group HEADER does nothing: it is not a page, and moving
    /// the cursor there would leave the sidebar on a row the arrows skip.
    #[test]
    fn a_click_on_a_group_header_does_nothing() {
        let mut s = state();
        let before = (s.cursor(), s.current().clone());
        let group = s
            .rows()
            .iter()
            .position(|r| matches!(r, SidebarRow::Group { .. }))
            .expect("there are group headers");
        s.click_row(group);
        assert_eq!((s.cursor(), s.current().clone()), before);
        // And an out-of-range index does not either: the painter can be one
        // frame behind the model.
        s.click_row(usize::MAX);
        assert_eq!((s.cursor(), s.current().clone()), before);
    }

    /// A click on a runnable row moves the action cursor and hands focus to
    /// the body — whether to run it is decided by the frontend, which is
    /// the one holding the frozen verdict.
    #[test]
    fn a_click_on_a_runnable_row_moves_the_action_cursor() {
        let mut s = state();
        s.open(&TopicId::new("copying"));
        assert!(s.actions().len() > 1, "`copying` has runnable rows");
        s.click_action(1);
        assert_eq!(s.action_cursor(), 1);
        assert_eq!(s.focus(), Focus::Body);
        let before = s.action_cursor();
        s.click_action(s.actions().len());
        assert_eq!(s.action_cursor(), before, "out of range is a no-op");
    }

    /// Dragging the scrollbar takes the body to an ABSOLUTE point, unlike
    /// the wheel, which is relative: a drag says "show me THIS part" and a
    /// notch says "a bit further".
    #[test]
    fn dragging_the_scrollbar_goes_to_an_absolute_line() {
        let mut s = state();
        s.scroll_body_to(40);
        assert_eq!(s.body_scroll(), 40);
        s.scroll_body_to(0);
        assert_eq!(
            s.body_scroll(),
            0,
            "and goes back to the start with no subtraction"
        );
        // The bottom cap is still set by the painter, which is the one that
        // knows how many lines the laid-out page has.
        s.scroll_body_to(9999);
        s.clamp_scroll(12);
        assert!(s.body_scroll() < 12);
    }

    /// The wheel moves the body no matter where focus is: it scrolls
    /// whatever is under the pointer, the same rule the panes follow.
    #[test]
    fn the_wheel_scrolls_the_body_with_focus_on_the_sidebar() {
        let mut s = state();
        assert_eq!(s.focus(), Focus::Topics);
        s.scroll_body(3);
        assert_eq!(s.body_scroll(), 3);
        s.scroll_body(-1);
        assert_eq!(s.body_scroll(), 2);
        s.scroll_body(-99);
        assert_eq!(s.body_scroll(), 0, "saturates at zero");
    }

    /// FIX 2: the keyboard page has to be findable by the name it is PAINTED
    /// with. Its label lives in the frontend's catalogue, so before this the
    /// filter only reached it through the literal `keys` and a reader typing
    /// the localized word watched the row they were looking at disappear.
    #[test]
    fn the_synthetic_keyboard_page_is_found_by_its_painted_label() {
        let mut s = state();
        assert!(
            s.rows().iter().any(|r| matches!(
                r,
                SidebarRow::Topic { id, title }
                    if id.as_str() == KEYS_ID && title == KEYS_LABEL
            )),
            "the synthetic row carries the frontend's label as its title"
        );
        for needle in ["keyb", "KEYBOARD", "board"] {
            s = state();
            s.start_filter();
            for c in needle.chars() {
                s.push_char(c);
            }
            assert!(
                shown(&s).iter().any(|id| id == KEYS_ID),
                "filtering by {needle:?} must keep the keyboard page: {:?}",
                shown(&s)
            );
        }
        // The id stays a match too, and so does the fallback for a frontend
        // that hands in nothing.
        s = state();
        s.start_filter();
        for c in "keys".chars() {
            s.push_char(c);
        }
        assert!(shown(&s).iter().any(|id| id == KEYS_ID));
        let blank = HelpState::new(Lang::En, String::new());
        assert!(blank.rows().iter().any(|r| matches!(
            r,
            SidebarRow::Topic { id, title }
                if id.as_str() == KEYS_ID && title == KEYS_ID
        )));
    }

    /// The ids the sidebar is showing, in row order.
    fn shown(s: &HelpState) -> Vec<String> {
        s.rows()
            .iter()
            .filter_map(|r| match r {
                SidebarRow::Topic { id, .. } => Some(id.as_str().to_owned()),
                SidebarRow::Group { .. } => None,
            })
            .collect()
    }

    #[test]
    fn opens_on_the_index_with_every_topic_in_the_sidebar() {
        let s = state();
        assert_eq!(s.current().as_str(), "index");

        // EVERY topic of the corpus, in corpus order, plus the synthetic
        // keyboard page last: a topic added to the corpus is in the sidebar
        // the same day, with nothing here to update.
        let mut expected: Vec<String> = norte_help::topic_ids(Lang::En)
            .iter()
            .map(|id| id.as_str().to_owned())
            .collect();
        expected.push(KEYS_ID.to_owned());
        assert_eq!(shown(&s), expected);
    }

    #[test]
    fn a_group_header_precedes_the_topics_of_its_tag() {
        let s = state();
        let first = s.rows().first().expect("a non-empty sidebar");
        assert!(
            matches!(first, SidebarRow::Group { .. }),
            "the sidebar opens with a group header: {first:?}"
        );
    }

    #[test]
    fn the_cursor_never_lands_on_a_group_header() {
        let mut s = state();
        for _ in 0..s.rows().len() * 2 {
            s.down();
            assert!(
                matches!(s.rows()[s.cursor()], SidebarRow::Topic { .. }),
                "cursor {} landed on a header",
                s.cursor()
            );
        }
        // And it STOPPED there: a wrapping stepper would satisfy every
        // assertion above and still throw the reader back to the top.
        assert_eq!(
            s.selected_topic().map(TopicId::as_str),
            Some(KEYS_ID),
            "walking off the bottom parks on the last entry"
        );
        for _ in 0..s.rows().len() * 2 {
            s.up();
            assert!(matches!(s.rows()[s.cursor()], SidebarRow::Topic { .. }));
        }
        assert_eq!(
            s.selected_topic().map(TopicId::as_str),
            Some("index"),
            "and off the top, on the first"
        );
    }

    #[test]
    fn arrowing_through_the_sidebar_is_not_navigation() {
        let mut s = state();
        for _ in 0..5 {
            s.down();
        }
        assert_ne!(s.current().as_str(), "index", "the preview did move");
        assert!(
            !s.back(),
            "previewing is not navigating: five arrow keys must not cost five \
             presses of Esc before the overlay can close"
        );
    }

    #[test]
    fn following_a_link_pushes_history_and_back_pops_it() {
        let mut s = state();
        s.open(&TopicId::new("copying"));
        s.open(&TopicId::new("archives"));
        assert_eq!(s.current().as_str(), "archives");
        assert!(s.back());
        assert_eq!(s.current().as_str(), "copying");
        assert!(s.back());
        assert_eq!(s.current().as_str(), "index");
        assert!(
            !s.back(),
            "no history left, and the caller must be able to tell"
        );
        assert_eq!(s.current().as_str(), "index");
    }

    /// H3c: the CONTEXTUAL open is not navigation the reader did, so it must
    /// not leave a step behind. `Esc` on a page `F1` chose for them has to
    /// close the overlay, never walk back to an index they never asked for.
    #[test]
    fn opening_as_root_leaves_nothing_for_back_to_walk() {
        // With history already stacked (`following_a_link_pushes_history_and_back_
        // pops_it` pins that half): arriving as root ERASES it, so the
        // `back()` that would have returned to `copying` now has nothing.
        let mut s = state();
        s.open(&TopicId::new("copying"));
        s.open_as_root(&TopicId::new("archives"));
        assert_eq!(s.current().as_str(), "archives", "the body does change");
        assert!(
            !s.back(),
            "arriving as root means \"back\" can only be closing"
        );

        // And a root that matches what is already open does not stack
        // either: `show` ignores the current id, and the clear does not
        // depend on it having changed.
        let mut s = state();
        s.open_as_root(&TopicId::new("index"));
        assert!(!s.back());
    }

    #[test]
    fn opening_an_unknown_topic_changes_nothing() {
        let mut s = state();
        s.open(&TopicId::new("no-such-topic"));
        assert_eq!(s.current().as_str(), "index");
        assert!(!s.back(), "a refused open must not push history either");
    }

    #[test]
    fn the_filter_keeps_topics_whose_title_id_or_command_matches() {
        let mut s = state();
        s.start_filter();
        for c in "copy".chars() {
            s.push_char(c);
        }
        // Owned ids: the backspaces below mutate `s` while these are still
        // named (the plan's `Vec<&str>` cannot outlive the `&s` it borrows).
        let ids = shown(&s);
        assert!(
            ids.iter().any(|id| id == "copying"),
            "matched by id and title: {ids:?}"
        );
        assert!(
            ids.iter().any(|id| id == "mouse"),
            "a page that DOCUMENTS pane.copy is a hit for `copy`, even though \
             neither its id nor its title says so: {ids:?}"
        );
        assert!(
            !ids.iter().any(|id| id == "index"),
            "a page that documents no command and is not named for one stays \
             out: {ids:?}"
        );
        s.backspace();
        s.backspace();
        s.backspace();
        s.backspace();
        assert_eq!(
            s.filter_raw(),
            "",
            "backspacing to empty restores everything"
        );
        assert_eq!(
            shown(&s),
            shown(&state()),
            "and `everything` is exactly what an untouched overlay shows"
        );
    }

    #[test]
    fn a_filter_that_matches_nothing_leaves_the_open_topic_alone() {
        let mut s = state();
        s.open(&TopicId::new("copying"));
        s.start_filter();
        // What the body shows the moment BEFORE the filter empties the
        // sidebar — which is not necessarily what was open when the filter
        // started. A prefix that still matches something moves the cursor to
        // the first survivor and the body follows it, deliberately; this
        // test is about the step after that, where nothing survives and
        // there is nowhere to follow to.
        //
        // It is read from the state rather than written down because the
        // corpus decides it: this used to hard-code `copying` and went red
        // the day a page documented a command with a `z` in it, which made
        // `z` a matching prefix. The invariant never involved that word.
        let mut last_vivo = s.current().clone();
        for c in "zzzz".chars() {
            if !s.rows().is_empty() {
                last_vivo = s.current().clone();
            }
            s.push_char(c);
        }
        assert!(s.rows().is_empty(), "nothing matched");
        assert_eq!(
            s.current(),
            &last_vivo,
            "the body keeps showing what the reader was reading"
        );
    }

    #[test]
    fn a_hostile_filter_is_matched_raw_and_displayed_masked() {
        let mut s = state();
        s.start_filter();
        s.push_char('\u{202E}');
        s.push_char('a');
        assert_eq!(s.filter_raw(), "\u{202E}a", "matching sees the raw bytes");
        assert!(
            !s.filter_display()
                .chars()
                .any(norte_encoding::is_terminal_hazard),
            "what is painted carries no hazard: {:?}",
            s.filter_display()
        );
    }

    #[test]
    fn focus_moves_between_the_panes_and_the_body_cursor_walks_actions() {
        let mut s = state();
        s.open(&TopicId::new("copying"));
        assert_eq!(s.focus(), Focus::Topics);
        s.toggle_focus();
        assert_eq!(s.focus(), Focus::Body);
        let first = s.action().cloned().expect("a first action");
        assert_eq!(first, Action::Run("pane.copy".to_owned()));
        s.down();
        assert_eq!(s.action(), Some(&Action::Run("pane.move".to_owned())));

        // The `see_also` links are the tail of the same list: deleting them
        // from `rebuild_actions` must fail here, not go unnoticed until a
        // reader wonders why a topic's own links cannot be followed.
        assert_eq!(
            s.actions().last(),
            Some(&Action::Open(TopicId::new("archives"))),
            "commands first, then the links, in declared order: {:?}",
            s.actions()
        );

        for _ in 0..50 {
            s.down();
        }
        assert_eq!(
            s.action_cursor(),
            s.actions().len() - 1,
            "walking off the end parks on the last action, and does NOT wrap"
        );
    }

    #[test]
    fn reveal_scrolls_the_least_it_can_and_paging_moves_the_body() {
        let mut s = state();
        s.open(&TopicId::new("copying"));
        assert_eq!(s.body_scroll(), 0);

        // Already inside the window: nothing moves.
        s.reveal(3, 10);
        assert_eq!(s.body_scroll(), 0);
        // Below it: the line becomes the last one painted.
        s.reveal(12, 10);
        assert_eq!(s.body_scroll(), 3);
        // Above it: the line becomes the first one painted.
        s.reveal(1, 10);
        assert_eq!(s.body_scroll(), 1);
        // A window of zero lines has nothing to reveal into.
        s.reveal(99, 0);
        assert_eq!(s.body_scroll(), 1);
        // An absurd line number saturates instead of aborting the process:
        // the line count comes from a laid-out body, and arithmetic that only
        // holds for plausible bodies is arithmetic that panics one day.
        s.reveal(usize::MAX, 10);
        assert_eq!(s.body_scroll(), usize::MAX - 9);
        s.reveal(usize::MAX, usize::MAX);
        s.reveal(0, 10);
        assert_eq!(s.body_scroll(), 0);

        s.toggle_focus();
        assert_eq!(s.focus(), Focus::Body);
        let action = s.action_cursor();
        s.page_down(20);
        s.clamp_scroll(12);
        assert_eq!(
            s.body_scroll(),
            11,
            "the renderer says how many lines it laid out, and the scroll \
             stops at the last one"
        );
        assert_eq!(
            s.action_cursor(),
            action,
            "a page is a movement over prose, not over actions"
        );
        s.page_down(1_000_000);
        s.clamp_scroll(12);
        assert_eq!(s.body_scroll(), 11, "a huge page cannot outrun the body");
        s.clamp_scroll(0);
        assert_eq!(s.body_scroll(), 0, "a body with no lines has no scroll");
        s.page_up(100);
        assert_eq!(s.body_scroll(), 0, "paging past the top stops at the top");
    }

    #[test]
    fn esc_leaves_the_search_box_without_undoing_the_search() {
        let mut s = state();
        s.start_filter();
        assert!(s.filtering());
        for c in "copy".chars() {
            s.push_char(c);
        }
        let filtered = s.rows().len();
        s.end_filter();
        assert!(!s.filtering());
        assert_eq!(s.filter_raw(), "copy", "the text survives leaving the box");
        assert_eq!(s.rows().len(), filtered, "and so does what it kept");
        // The open page (`index`) did not survive the filter, so the cursor
        // falls onto the first row that did — never onto a header, and never
        // off the end of a list that just shrank. The BODY follows it: the
        // highlight and what is being read are one thing, or the next arrow
        // key steps from a row the reader never saw opened.
        assert_eq!(
            s.selected_topic().map(TopicId::as_str),
            Some("mouse"),
            "the cursor sits on the first surviving topic"
        );
        assert_eq!(
            s.current().as_str(),
            "mouse",
            "and the body is showing exactly that topic"
        );

        // Typing outside the box is not typing into it (an invariant of the
        // type, not of whichever frontend routes the key).
        s.push_char('z');
        assert_eq!(s.filter_raw(), "copy");
        s.backspace();
        assert_eq!(s.filter_raw(), "copy");
    }

    /// Opening the filter takes the cursor back to the sidebar: the arrows
    /// inside the box walk the HITS. Reachable in the TUI with `Tab` then `/`
    /// — the index has seven `see_also` rows to move the focus into — and
    /// before this the arrows drove the body of the page underneath while the
    /// list the reader was narrowing could not be walked at all.
    #[test]
    fn opening_the_filter_hands_the_cursor_back_to_the_sidebar() {
        let mut s = state();
        s.toggle_focus();
        assert_eq!(s.focus(), Focus::Body, "the index has links to focus");
        s.start_filter();
        assert_eq!(s.focus(), Focus::Topics);

        // …and the arrows really do drive the list now.
        let before = s.selected_topic().cloned();
        s.down();
        assert_ne!(
            s.selected_topic().cloned(),
            before,
            "the sidebar cursor moved: {:?}",
            s.rows()
        );
    }

    #[test]
    fn the_keyboard_page_has_lines_and_no_actions() {
        let mut s = state();
        s.open(&TopicId::new(KEYS_ID));
        assert_eq!(s.current().as_str(), KEYS_ID);
        assert!(
            s.topic().is_none(),
            "the keyboard page is not a corpus topic"
        );
        s.toggle_focus();
        assert!(
            s.actions().is_empty(),
            "its rows are chords, and a chord is not something Enter runs"
        );
        assert_eq!(
            s.focus(),
            Focus::Body,
            "but the focus still MOVES: the keyboard page is the longest one, \
             and with the focus refused the page keys walked the sidebar \
             instead, so the cheatsheet could not be read past its first screen"
        );
        assert_eq!(s.action(), None);
    }

    fn filter_titles(s: &mut HelpState, text: &str) -> Vec<String> {
        s.start_filter();
        for c in text.chars() {
            s.push_char(c);
        }
        s.rows()
            .iter()
            .filter_map(|r| match r {
                SidebarRow::Topic { id, .. } => Some(id.as_str().to_owned()),
                SidebarRow::Group { .. } => None,
            })
            .collect()
    }

    /// With no accents it finds what has accents: «raton» is «ratón» for
    /// anyone typing in a hurry. Before this, 3 of the Spanish titles did
    /// not turn up without the exact accent.
    #[test]
    fn the_help_filter_does_not_distinguish_accents() {
        let mut s = HelpState::new(Lang::Es, "Teclado".to_owned());
        assert!(filter_titles(&mut s, "raton").contains(&"mouse".to_owned()));
        let mut s = HelpState::new(Lang::Es, "Teclado".to_owned());
        assert!(
            filter_titles(&mut s, "RATÓN").contains(&"mouse".to_owned()),
            "nor case"
        );
    }

    /// The filter also searches the TEXT of the pages: a word that only
    /// appears in the prose finds the page that explains it.
    #[test]
    fn the_filter_searches_the_text_of_the_pages() {
        let mut s = HelpState::new(Lang::Es, "Teclado".to_owned());
        let found = filter_titles(&mut s, "bucket");
        assert!(
            found.contains(&"index".to_owned()),
            "«bucket» is only in the index's prose (and remote's): {found:?}"
        );
        let mut s = HelpState::new(Lang::Es, "Teclado".to_owned());
        assert!(
            filter_titles(&mut s, "zzzqqq").is_empty(),
            "and what is not there does not turn up"
        );
    }

    /// The prose's own `[[links]]` are actions: they used to be painted as
    /// a link and could not be followed with either Enter or a click. The
    /// order is `Topic::links()`'s, which is what both frontends paint.
    #[test]
    fn the_links_in_the_prose_are_actions_too() {
        let mut some_extra = false;
        for t in norte_help::topics(Lang::En) {
            let mut s = state();
            s.open(&t.id);
            let expected: Vec<Action> = t
                .commands
                .iter()
                .cloned()
                .map(Action::Run)
                .chain(t.links().into_iter().map(Action::Open))
                .collect();
            assert_eq!(s.actions(), expected.as_slice(), "{}", t.id);
            some_extra |= t.links().len() > t.see_also.len();
        }
        assert!(
            some_extra,
            "some page links in its prose to something see_also does not name"
        );
    }

    #[test]
    fn top_and_bottom_go_to_the_ends_of_whichever_half_has_the_focus() {
        let mut s = state();
        s.open(&TopicId::new("copying"));
        // Sidebar: the first and the last PAGE, never a group header.
        s.bottom();
        let last = s.cursor();
        assert!(
            matches!(s.rows().get(last), Some(SidebarRow::Topic { .. })),
            "lands on a page"
        );
        assert!(
            s.rows()[last + 1..]
                .iter()
                .all(|r| !matches!(r, SidebarRow::Topic { .. })),
            "and it is the LAST page"
        );
        s.top();
        assert!(matches!(
            s.rows().get(s.cursor()),
            Some(SidebarRow::Topic { .. })
        ));
        assert!(
            s.rows()[..s.cursor()]
                .iter()
                .all(|r| !matches!(r, SidebarRow::Topic { .. })),
            "and it is the FIRST page"
        );

        // Body: the scroll, not the action cursor — reading, not choosing.
        s.open(&TopicId::new("copying"));
        s.toggle_focus();
        s.bottom();
        s.clamp_scroll_window(100, 20);
        assert_eq!(
            s.body_scroll(),
            80,
            "the last FULL screen, not the last line"
        );
        assert!(s.action_follows_view(), "the view leads after a jump");
        s.top();
        assert_eq!(s.body_scroll(), 0);
    }

    #[test]
    fn the_last_screen_is_full_and_a_short_page_does_not_scroll() {
        let mut s = state();
        s.scroll_body_to(95);
        s.clamp_scroll_window(100, 20);
        assert_eq!(
            s.body_scroll(),
            80,
            "clamping to the last LINE left a screen of blank rows under it"
        );
        s.clamp_scroll_window(12, 20);
        assert_eq!(
            s.body_scroll(),
            0,
            "a page shorter than the box has nowhere to go"
        );
    }

    #[test]
    fn scrolling_the_body_hands_the_lead_to_the_view() {
        // A wheel turn that the next refresh undid: with the action cursor
        // leading, the painter revealed its line again and snapped the page
        // back to it.
        let mut s = state();
        s.open(&TopicId::new("copying"));
        s.toggle_focus();
        s.down();
        assert!(!s.action_follows_view());
        s.scroll_body(3);
        assert!(s.action_follows_view());
        s.down();
        s.scroll_body_to(0);
        assert!(s.action_follows_view());
    }

    fn node(id: &str) -> PluginNode {
        PluginNode {
            id: id.to_owned(),
            title: format!("Título de {id}"),
            has_help: true,
            active: true,
        }
    }

    #[test]
    fn plugins_with_help_get_a_row_on_the_sidebar() {
        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        help.set_plugins(vec![node("acme.ftp")]);
        assert!(
            help.rows().iter().any(|r| matches!(
                r,
                SidebarRow::Topic { id, .. } if id.as_str() == "acme.ftp"
            )),
            "the plugin's node is on the sidebar: {:?}",
            help.rows()
        );
    }

    #[test]
    fn a_plugin_with_no_help_gets_no_row() {
        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        let mut n = node("acme.ftp");
        n.has_help = false;
        help.set_plugins(vec![n]);
        assert!(
            !help.rows().iter().any(|r| matches!(
                r,
                SidebarRow::Topic { id, .. } if id.as_str() == "acme.ftp"
            )),
            "with no page there is no node to open"
        );
    }

    /// Fail-closed: the corpus wins. The collision cannot arise TODAY from a
    /// locally-discovered plugin — `is_valid_plugin_id` requires reverse-DNS
    /// (two dot-separated segments) and every corpus id is a single segment,
    /// so a manifest with `id = "copying"` does not even load. The guard
    /// exists because THIS model receives ids that came from the WIRE and
    /// the id space is owned by another crate, which promises this one
    /// nothing: a `PluginNode` is a plain struct anyone —this test first—
    /// can construct. Without the guard, a plugin published as `copying`
    /// would eat the copy page and every `[[copying]]` in the corpus would
    /// land in third-party prose.
    #[test]
    fn a_plugin_does_not_cover_a_corpus_page() {
        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        help.set_plugins(vec![node("copying")]);
        help.open(&TopicId::new("copying"));
        let opened = help.current_topic().expect("there is a page");
        assert_eq!(opened.origin, norte_help::Origin::BuiltIn);
    }

    #[test]
    fn a_plugins_page_opens_once_it_arrives_from_the_wire() {
        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        help.set_plugins(vec![node("acme.ftp")]);
        help.open(&TopicId::new("acme.ftp"));
        assert_eq!(
            help.plugin_needs_fetch(),
            Some("acme.ftp"),
            "has not arrived yet"
        );
        assert!(help.current_topic().is_none(), "no body is invented");

        // `id` is REQUIRED in the header (`FrontMatter::id` has no
        // `#[serde(default)]`): without it the TOML fails to deserialize,
        // `parse_untrusted` degrades to "no header" —never to an error— and
        // both the title and the commands would be lost at once, which is
        // exactly what this test looks at. The declared id does not
        // matter: the one that governs is the one the host assigns.
        let parsed = norte_help::parse_untrusted(
            b"+++\nid = \"acme.ftp\"\ntitle = \"FTP\"\n\
              commands = [\"plugin:acme.ftp:sync\"]\n+++\nbody",
            "acme.ftp",
            None,
        );
        help.install_plugin_topic(parsed.topic);
        assert_eq!(help.plugin_needs_fetch(), None, "already installed");
        assert_eq!(help.current_topic().expect("there is a page").title, "FTP");
        assert_eq!(
            help.actions().first(),
            Some(&Action::Run("plugin:acme.ftp:sync".to_owned())),
            "its commands are runnable rows"
        );
    }

    #[test]
    fn switching_plugins_forgets_the_pages_that_are_gone() {
        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        help.set_plugins(vec![node("acme.ftp")]);
        let parsed = norte_help::parse_untrusted(b"body", "acme.ftp", None);
        help.install_plugin_topic(parsed.topic);
        help.set_plugins(vec![node("otro.plugin")]);
        help.open(&TopicId::new("acme.ftp"));
        assert_ne!(
            help.current().as_str(),
            "acme.ftp",
            "a plugin no longer in the catalogue does not open"
        );
    }

    /// Two nodes with the same id give ONE row, the first. `Catalog::load_dir`
    /// rejects a repeated id fail-closed, so a locally-discovered catalogue
    /// cannot produce one — but these nodes are built from `plugin.list`,
    /// which crosses the wire, and this model does not assume the peer
    /// enforced what our host enforces. Two rows opening the same page is a
    /// small harm; what is out of place is the assumption.
    #[test]
    fn two_nodes_with_the_same_id_give_a_single_row() {
        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        let mut impostor = node("acme.ftp");
        impostor.title = "The impostor".to_owned();
        help.set_plugins(vec![node("acme.ftp"), impostor]);
        let rows: Vec<&SidebarRow> = help
            .rows()
            .iter()
            .filter(|r| matches!(r, SidebarRow::Topic { id, .. } if id.as_str() == "acme.ftp"))
            .collect();
        assert_eq!(rows.len(), 1, "a single row: {:?}", help.rows());
        assert!(
            matches!(rows[0], SidebarRow::Topic { title, .. } if title == "Título de acme.ftp"),
            "and the FIRST one wins, the one the extension manager and the \
             palette already show: {:?}",
            rows[0]
        );
    }

    /// A page arriving late, for a plugin no longer in the catalogue, does
    /// not revive it: the catalogue is the truth about what exists, and an
    /// in-flight response cannot reopen a door that closed.
    #[test]
    fn a_page_for_a_plugin_that_is_not_a_node_is_ignored() {
        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        help.set_plugins(vec![node("otro.plugin")]);
        let parsed = norte_help::parse_untrusted(b"body", "acme.ftp", None);
        help.install_plugin_topic(parsed.topic);
        help.open(&TopicId::new("acme.ftp"));
        assert_ne!(help.current().as_str(), "acme.ftp");
        assert!(
            !help.rows().iter().any(|r| matches!(
                r,
                SidebarRow::Topic { id, .. } if id.as_str() == "acme.ftp"
            )),
            "nor does it show up on the sidebar"
        );
    }

    /// A plugin's row is filtered like any other: by id or by title.
    /// Otherwise the filter would leave the corpus list empty with the
    /// extensions dangling below it, which is exactly what the reader was
    /// NOT looking for.
    #[test]
    fn the_filter_reaches_and_drops_plugin_rows() {
        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        help.set_plugins(vec![node("acme.ftp")]);
        help.start_filter();
        for c in "acme".chars() {
            help.push_char(c);
        }
        assert!(
            shown(&help).iter().any(|id| id == "acme.ftp"),
            "the id reaches the row: {:?}",
            shown(&help)
        );

        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        help.set_plugins(vec![node("acme.ftp")]);
        help.start_filter();
        for c in "título".chars() {
            help.push_char(c);
        }
        assert!(
            shown(&help).iter().any(|id| id == "acme.ftp"),
            "and so does the title: {:?}",
            shown(&help)
        );

        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        help.set_plugins(vec![node("acme.ftp")]);
        help.start_filter();
        for c in "zzzz".chars() {
            help.push_char(c);
        }
        assert!(
            help.rows().is_empty(),
            "and what does not match is gone, header included: {:?}",
            help.rows()
        );
    }

    /// An inactive node (not approved, or disabled) STILL has a page: a
    /// human reads a plugin's documentation precisely to decide whether to
    /// enable it. What its state decides is whether its rows are runnable.
    #[test]
    fn an_inactive_plugin_keeps_its_page() {
        let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
        let mut n = node("acme.ftp");
        n.active = false;
        help.set_plugins(vec![n]);
        assert!(help.rows().iter().any(|r| matches!(
            r,
            SidebarRow::Topic { id, .. } if id.as_str() == "acme.ftp"
        )));
        help.open(&TopicId::new("acme.ftp"));
        assert!(!help.current_plugin_active(), "but it is not active");

        // A corpus page has no plugin that could be inactive.
        help.open(&TopicId::new("copying"));
        assert!(help.current_plugin_active());
    }

    #[test]
    fn a_hostile_title_is_matched_on_its_raw_bytes() {
        let hostile = Topic {
            id: TopicId::new("hostile"),
            title: "cop\u{202E}y".to_owned(),
            tags: Vec::new(),
            see_also: Vec::new(),
            commands: Vec::new(),
            context: Vec::new(),
            blocks: Vec::new(),
            origin: norte_help::Origin::BuiltIn,
        };

        // The needle is folded, never masked — and neither is the haystack.
        // Folding either side through `mask_terminal_hazards` would replace
        // the override with a placeholder on ONE side only, and a title the
        // reader can see on screen would stop being findable by typing it.
        assert!(matches(&hostile, &fold("cop\u{202E}y".as_bytes())));
        assert!(
            !matches(
                &hostile,
                &fold(mask_terminal_hazards("cop\u{202E}y").as_bytes())
            ),
            "the masked spelling is a DIFFERENT string; it is what gets \
             painted, never what gets matched"
        );
        assert!(
            matches(&hostile, &fold(b"cop")),
            "the plain prefix still hits"
        );
    }
}
