//! Navigation model of the help overlay (H3b): which topics the sidebar
//! shows, which one is open, what the filter keeps, where the reader has
//! been, and which action the cursor is on.
//!
//! Lives here and not in `norte-tui` for the reason the settings model (S4)
//! and the palette rows (G3c) live here: the GUI view of H3f is the SAME
//! model with a different painter, and a second copy in `norte-gui` would
//! drift from this one within a phase. Nothing in this module knows about
//! ratatui, GPUI or a terminal cell.
//!
//! Nothing here is user-facing text either: what comes out is ids and tags
//! (`SidebarRow::Group.tag`, [`Action::Run`]'s command id), and the frontend
//! turns each one into a Fluent string. That is what lets one model serve two
//! frontends that name the same thing differently.

use norte_encoding::mask_terminal_hazards;
use norte_help::{Lang, Topic, TopicId, topics};

use crate::nav::fold;

/// Id of the topic the overlay opens on.
const INDEX_ID: &str = "index";

/// Id of the synthetic keyboard page.
///
/// Not a corpus topic: its body is the effective keymap, generated by the
/// frontend (`norte_tui::help::build`), so it cannot be prose in a `.md`
/// file. It gets an id anyway because the sidebar, the history and the
/// filter all address entries by id, and a special case in each of them
/// would be three places to forget. H3h may replace it with a real topic;
/// nothing outside this module has to change if it does.
///
/// Having no corpus entry, it also has no corpus TITLE: the frontend hands
/// its localized label to [`HelpState::new`] and the row carries it like any
/// other title, so the filter reaches this page by the name it is painted
/// with (`teclado` finds it in Spanish) without this module ever touching
/// Fluent. The id stays a match too, and is the fallback when a frontend
/// passes a blank label.
pub const KEYS_ID: &str = "keys";

/// Tag the keyboard page is grouped under.
const KEYS_TAG: &str = "keys";

/// One row of the sidebar.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SidebarRow {
    /// Group header — the tag shared by the topics under it. NOT selectable.
    Group {
        /// The tag itself; the frontend translates it (`help-group-{tag}`).
        tag: String,
    },
    /// A topic the reader can open.
    Topic {
        /// Its id.
        id: TopicId,
        /// Its title, already the corpus' own (masked at parse for plugins).
        ///
        /// The one exception is the synthetic [`KEYS_ID`] entry, whose title
        /// is the label the frontend handed to [`HelpState::new`]: this
        /// module has no Fluent access on purpose. Painters can therefore
        /// print this field for EVERY row, with no special case, and the
        /// filter matches what is on screen.
        title: String,
    },
}

/// Which half of the overlay has the cursor.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Focus {
    /// The sidebar: up/down change the open topic.
    Topics,
    /// The body: up/down walk the runnable rows and links, Enter acts.
    Body,
}

/// What `Enter` does on the focused body row.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Action {
    /// Dispatch a command — the same id the palette sends.
    Run(String),
    /// Open another topic.
    Open(TopicId),
}

/// The overlay's whole state.
///
/// ```
/// use norte_frontend::help::{Focus, HelpState};
/// use norte_help::{Lang, TopicId};
///
/// // The label of the synthetic keyboard page comes from the frontend's own
/// // catalogue — this model never touches Fluent.
/// let mut help = HelpState::new(Lang::En, "Keyboard".to_owned());
/// assert_eq!(help.current().as_str(), "index");
/// assert_eq!(help.focus(), Focus::Topics);
///
/// // Following a link moves the body and remembers where the reader was.
/// help.open(&TopicId::new("copying"));
/// assert_eq!(help.current().as_str(), "copying");
/// assert!(help.back());
/// assert_eq!(help.current().as_str(), "index");
///
/// // A link the corpus cannot resolve is ignored, never a panic.
/// help.open(&TopicId::new("no-such-topic"));
/// assert_eq!(help.current().as_str(), "index");
/// ```
#[derive(Clone, Debug)]
pub struct HelpState {
    lang: Lang,
    /// Label of the synthetic [`KEYS_ID`] row, as the frontend paints it.
    keys_label: String,
    current: TopicId,
    history: Vec<TopicId>,
    rows: Vec<SidebarRow>,
    cursor: usize,
    filter: String,
    filtering: bool,
    focus: Focus,
    actions: Vec<Action>,
    action_cursor: usize,
    body_scroll: usize,
}

impl HelpState {
    /// Opens the overlay on the index topic of `lang`.
    ///
    /// `keys_label` is the title of the synthetic [`KEYS_ID`] row, already
    /// localized by the caller: this module has no Fluent access on purpose
    /// (the same page is named differently in the TUI and the GUI), so the
    /// label is data here like every corpus title, and the filter matches it
    /// like every corpus title. A blank label falls back to the id, which
    /// beats an empty sidebar row if a frontend ever forgets.
    ///
    /// See the type's own example: the constructor is where the reader lands,
    /// so its behaviour is documented there alongside what follows from it.
    #[must_use]
    pub fn new(lang: Lang, keys_label: String) -> Self {
        // The index is the entry point, but the corpus is data: if it ever
        // ships without one, opening on the first page beats opening on a
        // blank body that no key can leave.
        let current = topics(lang)
            .iter()
            .find(|t| t.id.as_str() == INDEX_ID)
            .or_else(|| topics(lang).first())
            .map_or_else(|| TopicId::new(KEYS_ID), |t| t.id.clone());
        let keys_label = if keys_label.trim().is_empty() {
            KEYS_ID.to_owned()
        } else {
            keys_label
        };
        let mut state = Self {
            lang,
            keys_label,
            current,
            history: Vec::new(),
            rows: Vec::new(),
            cursor: 0,
            filter: String::new(),
            filtering: false,
            focus: Focus::Topics,
            actions: Vec::new(),
            action_cursor: 0,
            body_scroll: 0,
        };
        state.rebuild_rows();
        state.rebuild_actions();
        state
    }

    /// Id of the topic the body is showing.
    #[must_use]
    pub fn current(&self) -> &TopicId {
        &self.current
    }

    /// The corpus locale this overlay was opened on.
    ///
    /// A painter needs it to resolve an id BACK to the page it names — a
    /// `see_also` row is painted with the topic's title, the same string the
    /// sidebar shows — and the corpus is keyed by language, so the id alone is
    /// not enough.
    ///
    /// ```
    /// use norte_frontend::help::HelpState;
    /// use norte_help::Lang;
    ///
    /// let help = HelpState::new(Lang::Es, "Teclado".to_owned());
    /// assert_eq!(help.lang(), Lang::Es);
    /// ```
    #[must_use]
    pub fn lang(&self) -> Lang {
        self.lang
    }

    /// The open corpus topic, or `None` for the synthetic [`KEYS_ID`] page
    /// (whose body the frontend generates from the effective keymap).
    #[must_use]
    pub fn topic(&self) -> Option<&'static Topic> {
        norte_help::topic(self.lang, self.current.as_str())
    }

    /// The sidebar as it stands under the current filter.
    #[must_use]
    pub fn rows(&self) -> &[SidebarRow] {
        &self.rows
    }

    /// Index into [`rows`](Self::rows) of the selected row. Always a
    /// [`SidebarRow::Topic`] while the sidebar has one.
    #[must_use]
    pub fn cursor(&self) -> usize {
        self.cursor
    }

    /// Which half of the overlay the cursor keys drive.
    #[must_use]
    pub fn focus(&self) -> Focus {
        self.focus
    }

    /// Everything the open topic offers: its commands, then its `see_also`.
    #[must_use]
    pub fn actions(&self) -> &[Action] {
        &self.actions
    }

    /// The action `Enter` would take, or `None` when the body does not hold
    /// the focus (the sidebar's `Enter` opens a topic, it does not run
    /// anything).
    #[must_use]
    pub fn action(&self) -> Option<&Action> {
        match self.focus {
            Focus::Body => self.actions.get(self.action_cursor),
            Focus::Topics => None,
        }
    }

    /// Index into [`actions`](Self::actions) of the focused body row.
    #[must_use]
    pub fn action_cursor(&self) -> usize {
        self.action_cursor
    }

    /// First body line the renderer should paint.
    #[must_use]
    pub fn body_scroll(&self) -> usize {
        self.body_scroll
    }

    /// Scrolls the body so that `line` sits inside a window of `height`
    /// lines, moving as little as possible.
    ///
    /// The height arrives from the caller because the renderer is the only
    /// side that knows it: this model has no idea how tall a terminal row or
    /// a GPUI line is, and guessing would make the two frontends scroll
    /// differently over the same topic. A `height` of zero is a no-op — there
    /// is no window to reveal anything in.
    ///
    /// Every step saturates. Both numbers come from a laid-out body, and
    /// arithmetic that only holds for plausible bodies is arithmetic that
    /// aborts the process the day one is not.
    pub fn reveal(&mut self, line: usize, height: usize) {
        if height == 0 {
            return;
        }
        if line < self.body_scroll {
            self.body_scroll = line;
        } else if line >= self.body_scroll.saturating_add(height) {
            // `line - (height - 1)`, ordered so that neither end can wrap and
            // the answer stays exact right up to `usize::MAX` (adding first
            // would saturate the +1 away and lose a line).
            self.body_scroll = line.saturating_sub(height.saturating_sub(1));
        }
    }

    /// Clamps the scroll to a body of `total` lines.
    ///
    /// The renderer calls this once per frame with the line count it just
    /// laid out. The count cannot live in this model — it depends on the
    /// width the prose was wrapped to, which is the one thing a render-
    /// agnostic model does not know — so [`page_down`](Self::page_down)
    /// deliberately does not bound itself and this is where the bound
    /// arrives, exactly as `height` arrives in [`reveal`](Self::reveal).
    /// Same idiom as the viewer's `total_rows` clamp.
    pub fn clamp_scroll(&mut self, total: usize) {
        self.body_scroll = self.body_scroll.min(total.saturating_sub(1));
    }

    /// Whether typed characters are going into the filter.
    #[must_use]
    pub fn filtering(&self) -> bool {
        self.filtering
    }

    /// The filter as typed: RAW, for MATCHING — and public because task 7
    /// hands it to the command palette, which matches on it too.
    ///
    /// `raw` is in the name on purpose. The one that may be painted is
    /// [`filter_display`](Self::filter_display); a bare `filter()` sitting
    /// next to a masked sibling is a trap for whoever writes the second
    /// frontend, and the cost of falling into it is a `U+202E` echoed into a
    /// terminal.
    #[must_use]
    pub fn filter_raw(&self) -> &str {
        &self.filter
    }

    /// The filter with terminal hazards masked, for painting.
    ///
    /// Matching and painting deliberately see different text: a needle
    /// carrying a bidi override must still find the topic the reader means
    /// (the corpus is folded raw too), but a `U+202E` echoed back into a
    /// terminal reorders the line it lands in.
    #[must_use]
    pub fn filter_display(&self) -> String {
        mask_terminal_hazards(&self.filter)
    }

    /// Routes typed characters into the filter, and hands the cursor back to
    /// the sidebar.
    ///
    /// Filtering is a SIDEBAR gesture: what the box narrows is the list of
    /// topics, and the arrow keys inside it are there to walk the hits. Left
    /// with the focus in the body they walked the ACTION cursor of the page
    /// underneath instead, and the list being filtered — the only thing on
    /// screen that had just changed — could not be walked at all. An invariant
    /// of the type rather than of each caller, on the same grounds as
    /// [`push_char`](Self::push_char)'s `filtering` guard.
    pub fn start_filter(&mut self) {
        self.filtering = true;
        self.focus = Focus::Topics;
    }

    /// Stops routing typed characters into the filter, KEEPING the text:
    /// `Esc` leaves the search box, it does not undo the search. Emptying it
    /// is what [`backspace`](Self::backspace) is for.
    pub fn end_filter(&mut self) {
        self.filtering = false;
    }

    /// Appends a character to the filter and rebuilds the sidebar. No-op
    /// unless [`filtering`](Self::filtering) — the caller already branches on
    /// that, but the guard here makes it an invariant OF THE TYPE and not of
    /// each of the three call sites (same criterion as `settings.rs`).
    pub fn push_char(&mut self, c: char) {
        if !self.filtering {
            return;
        }
        self.filter.push(c);
        self.rebuild_rows();
    }

    /// Drops the last character of the filter and rebuilds the sidebar. No-op
    /// while not [`filtering`](Self::filtering), like
    /// [`push_char`](Self::push_char).
    pub fn backspace(&mut self) {
        if !self.filtering {
            return;
        }
        self.filter.pop();
        self.rebuild_rows();
    }

    /// Opens `id`, remembering the current topic so [`back`](Self::back) can
    /// return to it.
    ///
    /// An id that resolves to nothing — a `see_also` or a `[[link]]` pointing
    /// at a page this locale's corpus does not have — is IGNORED: no history
    /// entry, no change of body, no panic. A dangling link in the prose is a
    /// corpus defect (`norte_help::check_corpus` catches it), and the reader
    /// pressing Enter on it is not the person who should find out.
    ///
    /// This is the NAVIGATING verb, and the only one that touches the
    /// history: a `[[link]]`, an [`Action::Open`], Enter on the sidebar.
    /// Merely arrowing the sidebar previews instead (see
    /// [`down`](Self::down)) — otherwise every keystroke of a scan through
    /// the index would owe the reader one press of `Esc` before the overlay
    /// could close.
    pub fn open(&mut self, id: &TopicId) {
        let previous = self.current.clone();
        self.show(id);
        if self.current != previous {
            self.history.push(previous);
        }
    }

    /// Goes back to the previously open topic. `false` when there is no
    /// history left, so the caller can decide what `Esc`/`Backspace` means
    /// then (the TUI closes the overlay).
    #[must_use]
    pub fn back(&mut self) -> bool {
        let Some(previous) = self.history.pop() else {
            return false;
        };
        self.current = previous;
        self.after_open();
        true
    }

    /// Moves the cursor one row up: one topic in the sidebar, one action in
    /// the body.
    pub fn up(&mut self) {
        match self.focus {
            Focus::Topics => self.move_sidebar(false, 1),
            Focus::Body => self.action_cursor = self.action_cursor.saturating_sub(1),
        }
    }

    /// Moves the cursor one row down: one topic in the sidebar, one action in
    /// the body.
    pub fn down(&mut self) {
        match self.focus {
            Focus::Topics => self.move_sidebar(true, 1),
            Focus::Body => self.clamp_action(self.action_cursor.saturating_add(1)),
        }
    }

    /// Moves `n` topics up in the sidebar, or scrolls the body `n` lines up.
    ///
    /// Paging the body moves the SCROLL and not the action cursor: a page is
    /// a movement over prose, and most of a topic is prose with no action on
    /// it at all.
    pub fn page_up(&mut self, n: usize) {
        match self.focus {
            Focus::Topics => self.move_sidebar(false, n),
            Focus::Body => self.body_scroll = self.body_scroll.saturating_sub(n),
        }
    }

    /// Moves `n` topics down in the sidebar, or scrolls the body `n` lines
    /// down. See [`page_up`](Self::page_up).
    pub fn page_down(&mut self, n: usize) {
        match self.focus {
            Focus::Topics => self.move_sidebar(true, n),
            Focus::Body => self.body_scroll = self.body_scroll.saturating_add(n),
        }
    }

    /// Hands the focus to the other half. Focusing a body with nothing
    /// runnable on it (the keyboard page, a topic with neither commands nor
    /// `see_also`) is a no-op: a focus the arrow keys cannot move is a dead
    /// end the reader has to guess their way out of.
    pub fn toggle_focus(&mut self) {
        self.focus = match self.focus {
            Focus::Body => Focus::Topics,
            Focus::Topics if self.actions.is_empty() => Focus::Topics,
            Focus::Topics => Focus::Body,
        };
    }

    /// Id under the sidebar cursor, or `None` when the filter left the
    /// sidebar empty.
    #[must_use]
    pub fn selected_topic(&self) -> Option<&TopicId> {
        match self.rows.get(self.cursor) {
            Some(SidebarRow::Topic { id, .. }) => Some(id),
            Some(SidebarRow::Group { .. }) | None => None,
        }
    }

    /// Opens whatever the sidebar cursor is on.
    pub fn open_selected(&mut self) {
        if let Some(id) = self.selected_topic().cloned() {
            self.open(&id);
        }
    }

    /// Whether `id` names something this overlay can show.
    fn exists(&self, id: &TopicId) -> bool {
        id.as_str() == KEYS_ID || norte_help::topic(self.lang, id.as_str()).is_some()
    }

    /// Shows `id` WITHOUT remembering where the reader was.
    ///
    /// The half of [`open`](Self::open) that changes the body. Previewing
    /// (arrowing the sidebar) and re-syncing after a filter both change what
    /// is on screen without being a place the reader chose to go, so neither
    /// of them may leave a step behind for `back()` to walk.
    ///
    /// An unknown id is ignored, and so is the id already open — the second
    /// guard is what keeps `open` from stacking a topic on top of itself.
    fn show(&mut self, id: &TopicId) {
        if *id == self.current || !self.exists(id) {
            return;
        }
        self.current = id.clone();
        self.after_open();
    }

    /// Common tail of [`open`](Self::open) and [`back`](Self::back): the body
    /// changed, so its actions, its scroll and the sidebar cursor follow it.
    fn after_open(&mut self) {
        self.body_scroll = 0;
        self.rebuild_actions();
        self.sync_cursor();
    }

    /// Rebuilds the sidebar from the corpus and the current filter.
    ///
    /// Corpus order, never alphabetical — the corpus is written in reading
    /// order and `norte_help::topic_ids` pins the same order in every locale.
    /// A header is emitted whenever the first tag CHANGES, so a tag that the
    /// corpus splits into two runs gets two headers: that is the table of
    /// contents the author wrote, and silently regrouping it would reorder
    /// the reading path.
    fn rebuild_rows(&mut self) {
        let needle = fold(self.filter.as_bytes());
        let mut rows: Vec<SidebarRow> = Vec::new();
        let mut group: Option<&str> = None;
        for topic in topics(self.lang) {
            if !matches(topic, &needle) {
                continue;
            }
            let tag = topic.tags.first().map_or("", String::as_str);
            if group != Some(tag) {
                // An untagged topic gets NO header: the tag is a Fluent key
                // stem (`help-group-{tag}`), and an empty one would send the
                // frontend looking up `help-group-`, which resolves to
                // nothing and paints as a stray blank band.
                if !tag.is_empty() {
                    rows.push(SidebarRow::Group {
                        tag: tag.to_owned(),
                    });
                }
                group = Some(tag);
            }
            rows.push(SidebarRow::Topic {
                id: topic.id.clone(),
                title: topic.title.clone(),
            });
        }
        // Same rule as [`matches`] applies to the corpus: id OR title. The
        // title here is the frontend's own label, so a reader who types what
        // the row SAYS (`tecl…` against `Teclado`) finds the row they are
        // looking straight at — before, only the literal `keys` reached it.
        if needle.is_empty()
            || fold(KEYS_ID.as_bytes()).contains(&needle)
            || fold(self.keys_label.as_bytes()).contains(&needle)
        {
            rows.push(SidebarRow::Group {
                tag: KEYS_TAG.to_owned(),
            });
            rows.push(SidebarRow::Topic {
                id: TopicId::new(KEYS_ID),
                title: self.keys_label.clone(),
            });
        }
        self.rows = rows;
        self.sync_cursor();

        // The highlight and the body are ONE thing. When the filter hides the
        // open topic the cursor lands on the first survivor, and the body has
        // to follow it there — otherwise the sidebar highlights `mouse` over
        // a body still showing `index`, and the next arrow key steps away
        // from a row the reader never saw opened. Not history: the reader
        // typed a letter, they did not choose to go anywhere.
        //
        // When NOTHING survived there is nowhere to follow to, and the body
        // keeps showing what was being read.
        //
        // The reverse direction is deliberately NOT symmetric: opening a
        // topic the current filter hides (a `see_also` link out of a filtered
        // list) keeps the body on the topic the reader chose and leaves the
        // highlight on the nearest visible row — there is no row to move it
        // to. A renderer that wants to say so compares `selected_topic()`
        // with `current()`.
        if self.row_of(&self.current).is_none()
            && let Some(landed) = self.selected_topic().cloned()
        {
            self.show(&landed);
        }
    }

    /// Puts the cursor back on the open topic, or on the first selectable row
    /// when the filter hid it. Never on a header, never out of bounds.
    fn sync_cursor(&mut self) {
        self.cursor = self
            .row_of(&self.current)
            .or_else(|| self.next_topic_row(0, true, true))
            .unwrap_or(0);
        debug_assert!(
            self.rows.is_empty()
                || matches!(self.rows.get(self.cursor), Some(SidebarRow::Topic { .. })),
            "the cursor must sit on a selectable row: {} of {:?}",
            self.cursor,
            self.rows
        );
    }

    /// Index of `id`'s row, if the sidebar is showing it.
    fn row_of(&self, id: &TopicId) -> Option<usize> {
        self.rows.iter().position(|row| match row {
            SidebarRow::Topic { id: row_id, .. } => row_id == id,
            SidebarRow::Group { .. } => false,
        })
    }

    /// Next selectable row from `from` in the given direction, skipping group
    /// headers. `inclusive` also considers `from` itself, which is what makes
    /// this usable both to step (exclusive) and to land (inclusive).
    /// `None` at the ends: the sidebar does NOT wrap.
    fn next_topic_row(&self, from: usize, forward: bool, inclusive: bool) -> Option<usize> {
        let mut i = from;
        if !inclusive {
            i = if forward {
                i.checked_add(1)?
            } else {
                i.checked_sub(1)?
            };
        }
        loop {
            match self.rows.get(i) {
                Some(SidebarRow::Topic { .. }) => return Some(i),
                Some(SidebarRow::Group { .. }) => {
                    i = if forward {
                        i.checked_add(1)?
                    } else {
                        i.checked_sub(1)?
                    };
                }
                None => return None,
            }
        }
    }

    /// Moves the sidebar cursor `n` selectable rows, stopping at the ends.
    ///
    /// The cursor SHOWS what it lands on (preview semantics, the same as the
    /// theme picker): arrowing through the index has to show each page, not
    /// make the reader press Enter on every line to find out what it is. It
    /// shows and does not [`open`](Self::open) — a preview leaves no step in
    /// the history, see [`show`](Self::show).
    fn move_sidebar(&mut self, forward: bool, n: usize) {
        let mut cursor = self.cursor;
        for _ in 0..n {
            match self.next_topic_row(cursor, forward, false) {
                Some(next) => cursor = next,
                None => break,
            }
        }
        self.cursor = cursor;
        if let Some(landed) = self.selected_topic().cloned() {
            self.show(&landed);
        }
    }

    /// Puts the body cursor on `wanted`, clamped to the last action.
    fn clamp_action(&mut self, wanted: usize) {
        self.action_cursor = wanted.min(self.actions.len().saturating_sub(1));
    }

    /// Rebuilds what `Enter` can do on the open topic: its commands in
    /// declared order, then its `see_also` links. Empty for the keyboard page
    /// — its rows are chords, and a chord is not something you press Enter on.
    fn rebuild_actions(&mut self) {
        self.actions = self.topic().map_or_else(Vec::new, |topic| {
            topic
                .commands
                .iter()
                .cloned()
                .map(Action::Run)
                .chain(topic.see_also.iter().cloned().map(Action::Open))
                .collect()
        });
        self.action_cursor = 0;
        if self.actions.is_empty() {
            self.focus = Focus::Topics;
        }
    }
}

/// Whether `topic` survives the (already folded) `needle`.
///
/// Id and title match by substring, like the palette and the quick search.
/// A command matches by PREFIX, deliberately: command ids are dotted keys,
/// and a substring rule makes `copy` drag in every page that merely mentions
/// `pane.copy` in passing — `mouse` documents it for ctrl-click — so the page
/// actually named "copying" arrives buried among them. Typing the key
/// (`pane.co`, `task.cancel`) still finds the page that documents it, which
/// is what matching commands at all was for.
///
/// # Known gap: diacritics
///
/// [`fold`] normalizes to NFC and lowercases; it does NOT strip diacritics.
/// So a needle typed without accents misses a title that has them: `como`
/// does not find «Cómo se lee esta ayuda» and `raton` does not find «Usar el
/// ratón» — 3 of the 8 Spanish titles as the corpus stands. Typing the accent
/// works, and so does any accent-free substring of the same title (`se lee`,
/// `usar el`), so no page is unreachable; it is worse than that for the
/// reader who does not know that.
///
/// Deliberately NOT fixed here. [`fold`] is ONE pipeline shared with the
/// filename path (quick search, `nav`), and there a name is BYTES: `café` and
/// `cafe` are two different files that must stay two different rows, so
/// folding the accent away would make the filename filter lie about what is
/// on disk. Splitting the two would mean a second normalization pipeline and
/// a second cache, and the choice of which surface gets which rule is a
/// design decision this phase is not the place to take. The next phase that
/// touches help search should take it explicitly — decompose to NFD and drop
/// `Mn` for the HELP needle only, or accept the gap and say so in the docs.
fn matches(topic: &Topic, needle: &str) -> bool {
    if needle.is_empty() {
        return true;
    }
    fold(topic.id.as_str().as_bytes()).contains(needle)
        || fold(topic.title.as_bytes()).contains(needle)
        || topic.commands.iter().any(|c| command_matches(c, needle))
}

/// A command matches when the needle is a prefix of its full id or of any of
/// its dot-separated SEGMENTS.
///
/// Segment-aware and not a plain `contains`, for the reason the palette's key
/// and text are kept apart: `co` should find `pane.copy`, and a reader who
/// types `copy` is looking for the copy key, not for every id with those four
/// letters somewhere inside. Prefix-only over the WHOLE id would be worse than
/// either — nobody types `pane.` before the verb, so the command half of the
/// filter would never fire for the word people actually search for.
///
/// A page that documents a command therefore surfaces for it, even when the
/// word is nowhere in its prose: searching `copy` finds the mouse page,
/// because dragging between panes IS a copy and that page is where it is
/// explained.
fn command_matches(command: &str, needle: &str) -> bool {
    let folded = fold(command.as_bytes());
    folded.starts_with(needle) || folded.split('.').any(|segment| segment.starts_with(needle))
}

#[cfg(test)]
mod tests {
    use super::*;
    use norte_help::{Lang, TopicId};

    /// The label the TUI would hand in, standing in for `t("help-topic-keys")`
    /// — deliberately NOT the id, so a test that passes by matching `keys`
    /// cannot pass by accident.
    const KEYS_LABEL: &str = "Keyboard";

    fn state() -> HelpState {
        HelpState::new(Lang::En, KEYS_LABEL.to_owned())
    }

    /// FIX 2: the keyboard page has to be findable by the name it is PAINTED
    /// with. Its label lives in the frontend's catalogue, so before this the
    /// filter only reached it through the literal `keys` and a reader typing
    /// the localized word watched the row they were looking at disappear.
    #[test]
    fn the_synthetic_keyboard_page_is_found_by_its_painted_label() {
        let mut s = state();
        assert!(
            s.rows().iter().any(|r| matches!(
                r,
                SidebarRow::Topic { id, title }
                    if id.as_str() == KEYS_ID && title == KEYS_LABEL
            )),
            "the synthetic row carries the frontend's label as its title"
        );
        for needle in ["keyb", "KEYBOARD", "board"] {
            s = state();
            s.start_filter();
            for c in needle.chars() {
                s.push_char(c);
            }
            assert!(
                shown(&s).iter().any(|id| id == KEYS_ID),
                "filtering by {needle:?} must keep the keyboard page: {:?}",
                shown(&s)
            );
        }
        // The id stays a match too, and so does the fallback for a frontend
        // that hands in nothing.
        s = state();
        s.start_filter();
        for c in "keys".chars() {
            s.push_char(c);
        }
        assert!(shown(&s).iter().any(|id| id == KEYS_ID));
        let blank = HelpState::new(Lang::En, String::new());
        assert!(blank.rows().iter().any(|r| matches!(
            r,
            SidebarRow::Topic { id, title }
                if id.as_str() == KEYS_ID && title == KEYS_ID
        )));
    }

    /// The ids the sidebar is showing, in row order.
    fn shown(s: &HelpState) -> Vec<String> {
        s.rows()
            .iter()
            .filter_map(|r| match r {
                SidebarRow::Topic { id, .. } => Some(id.as_str().to_owned()),
                SidebarRow::Group { .. } => None,
            })
            .collect()
    }

    #[test]
    fn opens_on_the_index_with_every_topic_in_the_sidebar() {
        let s = state();
        assert_eq!(s.current().as_str(), "index");

        // EVERY topic of the corpus, in corpus order, plus the synthetic
        // keyboard page last: a topic added to the corpus is in the sidebar
        // the same day, with nothing here to update.
        let mut expected: Vec<String> = norte_help::topic_ids(Lang::En)
            .iter()
            .map(|id| id.as_str().to_owned())
            .collect();
        expected.push(KEYS_ID.to_owned());
        assert_eq!(shown(&s), expected);
    }

    #[test]
    fn a_group_header_precedes_the_topics_of_its_tag() {
        let s = state();
        let first = s.rows().first().expect("a non-empty sidebar");
        assert!(
            matches!(first, SidebarRow::Group { .. }),
            "the sidebar opens with a group header: {first:?}"
        );
    }

    #[test]
    fn the_cursor_never_lands_on_a_group_header() {
        let mut s = state();
        for _ in 0..s.rows().len() * 2 {
            s.down();
            assert!(
                matches!(s.rows()[s.cursor()], SidebarRow::Topic { .. }),
                "cursor {} landed on a header",
                s.cursor()
            );
        }
        // And it STOPPED there: a wrapping stepper would satisfy every
        // assertion above and still throw the reader back to the top.
        assert_eq!(
            s.selected_topic().map(TopicId::as_str),
            Some(KEYS_ID),
            "walking off the bottom parks on the last entry"
        );
        for _ in 0..s.rows().len() * 2 {
            s.up();
            assert!(matches!(s.rows()[s.cursor()], SidebarRow::Topic { .. }));
        }
        assert_eq!(
            s.selected_topic().map(TopicId::as_str),
            Some("index"),
            "and off the top, on the first"
        );
    }

    #[test]
    fn arrowing_through_the_sidebar_is_not_navigation() {
        let mut s = state();
        for _ in 0..5 {
            s.down();
        }
        assert_ne!(s.current().as_str(), "index", "the preview did move");
        assert!(
            !s.back(),
            "previewing is not navigating: five arrow keys must not cost five \
             presses of Esc before the overlay can close"
        );
    }

    #[test]
    fn following_a_link_pushes_history_and_back_pops_it() {
        let mut s = state();
        s.open(&TopicId::new("copying"));
        s.open(&TopicId::new("archives"));
        assert_eq!(s.current().as_str(), "archives");
        assert!(s.back());
        assert_eq!(s.current().as_str(), "copying");
        assert!(s.back());
        assert_eq!(s.current().as_str(), "index");
        assert!(
            !s.back(),
            "no history left, and the caller must be able to tell"
        );
        assert_eq!(s.current().as_str(), "index");
    }

    #[test]
    fn opening_an_unknown_topic_changes_nothing() {
        let mut s = state();
        s.open(&TopicId::new("no-such-topic"));
        assert_eq!(s.current().as_str(), "index");
        assert!(!s.back(), "a refused open must not push history either");
    }

    #[test]
    fn the_filter_keeps_topics_whose_title_id_or_command_matches() {
        let mut s = state();
        s.start_filter();
        for c in "copy".chars() {
            s.push_char(c);
        }
        // Owned ids: the backspaces below mutate `s` while these are still
        // named (the plan's `Vec<&str>` cannot outlive the `&s` it borrows).
        let ids = shown(&s);
        assert!(
            ids.iter().any(|id| id == "copying"),
            "matched by id and title: {ids:?}"
        );
        assert!(
            ids.iter().any(|id| id == "mouse"),
            "a page that DOCUMENTS pane.copy is a hit for `copy`, even though \
             neither its id nor its title says so: {ids:?}"
        );
        assert!(
            !ids.iter().any(|id| id == "index"),
            "a page that documents no command and is not named for one stays \
             out: {ids:?}"
        );
        s.backspace();
        s.backspace();
        s.backspace();
        s.backspace();
        assert_eq!(
            s.filter_raw(),
            "",
            "backspacing to empty restores everything"
        );
        assert_eq!(
            shown(&s),
            shown(&state()),
            "and `everything` is exactly what an untouched overlay shows"
        );
    }

    #[test]
    fn a_filter_that_matches_nothing_leaves_the_open_topic_alone() {
        let mut s = state();
        s.open(&TopicId::new("copying"));
        s.start_filter();
        for c in "zzzz".chars() {
            s.push_char(c);
        }
        assert!(s.rows().is_empty(), "nothing matched");
        assert_eq!(
            s.current().as_str(),
            "copying",
            "the body keeps showing what the reader was reading"
        );
    }

    #[test]
    fn a_hostile_filter_is_matched_raw_and_displayed_masked() {
        let mut s = state();
        s.start_filter();
        s.push_char('\u{202E}');
        s.push_char('a');
        assert_eq!(s.filter_raw(), "\u{202E}a", "matching sees the raw bytes");
        assert!(
            !s.filter_display()
                .chars()
                .any(norte_encoding::is_terminal_hazard),
            "what is painted carries no hazard: {:?}",
            s.filter_display()
        );
    }

    #[test]
    fn focus_moves_between_the_panes_and_the_body_cursor_walks_actions() {
        let mut s = state();
        s.open(&TopicId::new("copying"));
        assert_eq!(s.focus(), Focus::Topics);
        s.toggle_focus();
        assert_eq!(s.focus(), Focus::Body);
        let first = s.action().cloned().expect("a first action");
        assert_eq!(first, Action::Run("pane.copy".to_owned()));
        s.down();
        assert_eq!(s.action(), Some(&Action::Run("pane.move".to_owned())));

        // The `see_also` links are the tail of the same list: deleting them
        // from `rebuild_actions` must fail here, not go unnoticed until a
        // reader wonders why a topic's own links cannot be followed.
        assert_eq!(
            s.actions().last(),
            Some(&Action::Open(TopicId::new("archives"))),
            "commands first, then the links, in declared order: {:?}",
            s.actions()
        );

        for _ in 0..50 {
            s.down();
        }
        assert_eq!(
            s.action_cursor(),
            s.actions().len() - 1,
            "walking off the end parks on the last action, and does NOT wrap"
        );
    }

    #[test]
    fn reveal_scrolls_the_least_it_can_and_paging_moves_the_body() {
        let mut s = state();
        s.open(&TopicId::new("copying"));
        assert_eq!(s.body_scroll(), 0);

        // Already inside the window: nothing moves.
        s.reveal(3, 10);
        assert_eq!(s.body_scroll(), 0);
        // Below it: the line becomes the last one painted.
        s.reveal(12, 10);
        assert_eq!(s.body_scroll(), 3);
        // Above it: the line becomes the first one painted.
        s.reveal(1, 10);
        assert_eq!(s.body_scroll(), 1);
        // A window of zero lines has nothing to reveal into.
        s.reveal(99, 0);
        assert_eq!(s.body_scroll(), 1);
        // An absurd line number saturates instead of aborting the process:
        // the line count comes from a laid-out body, and arithmetic that only
        // holds for plausible bodies is arithmetic that panics one day.
        s.reveal(usize::MAX, 10);
        assert_eq!(s.body_scroll(), usize::MAX - 9);
        s.reveal(usize::MAX, usize::MAX);
        s.reveal(0, 10);
        assert_eq!(s.body_scroll(), 0);

        s.toggle_focus();
        assert_eq!(s.focus(), Focus::Body);
        let action = s.action_cursor();
        s.page_down(20);
        s.clamp_scroll(12);
        assert_eq!(
            s.body_scroll(),
            11,
            "the renderer says how many lines it laid out, and the scroll \
             stops at the last one"
        );
        assert_eq!(
            s.action_cursor(),
            action,
            "a page is a movement over prose, not over actions"
        );
        s.page_down(1_000_000);
        s.clamp_scroll(12);
        assert_eq!(s.body_scroll(), 11, "a huge page cannot outrun the body");
        s.clamp_scroll(0);
        assert_eq!(s.body_scroll(), 0, "a body with no lines has no scroll");
        s.page_up(100);
        assert_eq!(s.body_scroll(), 0, "paging past the top stops at the top");
    }

    #[test]
    fn esc_leaves_the_search_box_without_undoing_the_search() {
        let mut s = state();
        s.start_filter();
        assert!(s.filtering());
        for c in "copy".chars() {
            s.push_char(c);
        }
        let filtered = s.rows().len();
        s.end_filter();
        assert!(!s.filtering());
        assert_eq!(s.filter_raw(), "copy", "the text survives leaving the box");
        assert_eq!(s.rows().len(), filtered, "and so does what it kept");
        // The open page (`index`) did not survive the filter, so the cursor
        // falls onto the first row that did — never onto a header, and never
        // off the end of a list that just shrank. The BODY follows it: the
        // highlight and what is being read are one thing, or the next arrow
        // key steps from a row the reader never saw opened.
        assert_eq!(
            s.selected_topic().map(TopicId::as_str),
            Some("mouse"),
            "the cursor sits on the first surviving topic"
        );
        assert_eq!(
            s.current().as_str(),
            "mouse",
            "and the body is showing exactly that topic"
        );

        // Typing outside the box is not typing into it (an invariant of the
        // type, not of whichever frontend routes the key).
        s.push_char('z');
        assert_eq!(s.filter_raw(), "copy");
        s.backspace();
        assert_eq!(s.filter_raw(), "copy");
    }

    /// Opening the filter takes the cursor back to the sidebar: the arrows
    /// inside the box walk the HITS. Reachable in the TUI with `Tab` then `/`
    /// — the index has seven `see_also` rows to move the focus into — and
    /// before this the arrows drove the body of the page underneath while the
    /// list the reader was narrowing could not be walked at all.
    #[test]
    fn opening_the_filter_hands_the_cursor_back_to_the_sidebar() {
        let mut s = state();
        s.toggle_focus();
        assert_eq!(s.focus(), Focus::Body, "the index has links to focus");
        s.start_filter();
        assert_eq!(s.focus(), Focus::Topics);

        // …and the arrows really do drive the list now.
        let before = s.selected_topic().cloned();
        s.down();
        assert_ne!(
            s.selected_topic().cloned(),
            before,
            "the sidebar cursor moved: {:?}",
            s.rows()
        );
    }

    #[test]
    fn the_keyboard_page_has_lines_and_no_actions() {
        let mut s = state();
        s.open(&TopicId::new(KEYS_ID));
        assert_eq!(s.current().as_str(), KEYS_ID);
        assert!(
            s.topic().is_none(),
            "the keyboard page is not a corpus topic"
        );
        s.toggle_focus();
        assert!(
            s.actions().is_empty(),
            "its rows are chords, and a chord is not something Enter runs"
        );
        assert_eq!(
            s.focus(),
            Focus::Topics,
            "so the focus REFUSED to move: a body the arrow keys cannot move \
             is a dead end"
        );
        assert_eq!(s.action(), None);
    }

    #[test]
    fn a_hostile_title_is_matched_on_its_raw_bytes() {
        let hostile = Topic {
            id: TopicId::new("hostile"),
            title: "cop\u{202E}y".to_owned(),
            tags: Vec::new(),
            see_also: Vec::new(),
            commands: Vec::new(),
            context: Vec::new(),
            blocks: Vec::new(),
            origin: norte_help::Origin::BuiltIn,
        };

        // The needle is folded, never masked — and neither is the haystack.
        // Folding either side through `mask_terminal_hazards` would replace
        // the override with a placeholder on ONE side only, and a title the
        // reader can see on screen would stop being findable by typing it.
        assert!(matches(&hostile, &fold("cop\u{202E}y".as_bytes())));
        assert!(
            !matches(
                &hostile,
                &fold(mask_terminal_hazards("cop\u{202E}y").as_bytes())
            ),
            "the masked spelling is a DIFFERENT string; it is what gets \
             painted, never what gets matched"
        );
        assert!(
            matches(&hostile, &fold(b"cop")),
            "the plain prefix still hits"
        );
    }
}
