//! The `sha256sum` format as seen from a frontend (#311): reading it,
//! writing it and comparing against it.
//!
//! It is text written by OTHERS — whoever distributes the file publishes
//! it — so it is parsed defensively: a line that does not fit is skipped
//! instead of taking down the whole file, because a `SHA256SUMS` with a PGP
//! signature glued in front or a comment at the end is still perfectly
//! checkable.
//!
//! **Skipping a line is COUNTED.** What was not understood cannot vanish:
//! the summary "N checked, all correct" over the survivors is a false
//! green, and the line that fell out is exactly the one with the odd name,
//! which is the one an attacker would control.
//!
//! # Names are BYTES (rule 1)
//!
//! A sums file is a list of names, and a name does not have to be text.
//! Here it is parsed over bytes and the name comes out as `Vec<u8>`: going
//! through `String` would turn `caf\xE9.txt` into a name with `U+FFFD` that
//! does not exist on disk, and the check would say "missing" about a file
//! that is right there. Writing has the same problem in reverse, which is
//! why [`to_sums_bytes`] produces BYTES and not a `String`.

/// Length of a sha256 in hex.
const SHA256_HEX: usize = 64;

/// A line of the sums file: the digest and the name it refers to.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SumLine {
    /// The digest as it came, already lowercase.
    pub digest: String,
    /// The name, in BYTES and relative to the sums file's directory.
    pub name: Vec<u8>,
}

/// What came out of reading a sums file.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ParsedSums {
    /// The lines that were understood, in the file's order.
    pub lines: Vec<SumLine>,
    /// How many lines LOOKED like sums and could not be read.
    ///
    /// A comment or a PGP header do not count here: they never claimed to
    /// be a sum. This counts what carried a digest in front and still did
    /// not fit, which is what cannot be kept quiet — checking 37 of 40
    /// lines and saying "40 correct" is the wrong answer from the one tool
    /// whose job is checking.
    pub refused: usize,
}

/// Whether these bytes are a UTF-16 text file (BOM at the start).
///
/// Exists so it can be SAID why no line came out: it is what
/// `Get-FileHash | Out-File` writes in PowerShell by default, and "this
/// does not look like a sums file" about a perfectly valid sums file in a
/// different encoding sends the reader to look for the problem in the
/// wrong place.
#[must_use]
pub fn looks_utf16(bytes: &[u8]) -> bool {
    matches!(bytes.first_chunk::<2>(), Some([0xFF, 0xFE] | [0xFE, 0xFF]))
}

/// Reads a sums file in `sha256sum` style.
///
/// Accepts the shapes real tools produce:
///
/// - `digest␠␠name` (text) and `digest␠*name` (binary);
/// - coreutils' ESCAPED shape, `\digest␠␠na\\me`, which is what
///   `sha256sum` writes when the name carries `\`, LF or CR — without this,
///   the file with the hostile name was not checked AND WAS NOT EVEN
///   LISTED;
/// - the BSD/`--tag` shape, `SHA256 (name) = digest`, which `sha256sum -c`
///   also reads;
/// - CRLF and a UTF-8 BOM at the start (a file generated on Windows lost
///   its first line silently).
///
/// The digest is normalized to lowercase: some publish it uppercase, and
/// two spellings of the same hash comparing differently is a bug waiting
/// to happen.
///
/// ```
/// use norte_frontend::checksums::parse_sums;
/// let text = b"# generated by hand\n\
///               e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  empty\n";
/// let read = parse_sums(text);
/// assert_eq!(read.lines.len(), 1);
/// assert_eq!(read.lines[0].name, b"empty");
/// assert_eq!(read.refused, 0, "a comment is not a rejected line");
/// ```
#[must_use]
pub fn parse_sums(bytes: &[u8]) -> ParsedSums {
    // UTF-8 BOM: swallowed by the first line's prefix, taking its hex with
    // it.
    let bytes = bytes.strip_prefix(b"\xEF\xBB\xBF").unwrap_or(bytes);
    let mut out = ParsedSums::default();
    for line in bytes.split(|b| *b == b'\n') {
        // Trailing CR from a file written on Windows: gone before anything
        // else, or the NAME's last byte would be a carriage return.
        let line = line.strip_suffix(b"\r").unwrap_or(line);
        if line.is_empty() || line.first() == Some(&b'#') {
            continue;
        }
        // The escaped shape carries a `\` IN FRONT of the digest, and the
        // name comes with `\\`, `\n` and `\r` inside.
        let (line, escaped) = match line.strip_prefix(b"\\") {
            Some(rest) => (rest, true),
            None => (line, false),
        };
        if let Some(l) = normal_line(line, escaped) {
            out.lines.push(l);
        } else if let Some(l) = bsd_line(line) {
            out.lines.push(l);
        } else if looked_like_a_sum(line) {
            // It carried a digest in front and still did not fit: that is
            // not kept quiet.
            out.refused += 1;
        }
    }
    out
}

/// `digest␠␠name` / `digest␠*name`, with the name unescaped if the line
/// came marked.
fn normal_line(line: &[u8], escaped: bool) -> Option<SumLine> {
    // 64 of hex + 2 of separator + 1 of name, at minimum.
    if line.len() < SHA256_HEX + 3 {
        return None;
    }
    let (hex, rest) = line.split_at(SHA256_HEX);
    if !hex.iter().all(u8::is_ascii_hexdigit) {
        return None;
    }
    // `sha256sum`'s separator is TWO characters: space + (space or `*`).
    // Anything else is not one of its lines, and guessing would mean
    // inventing a name that starts with a space.
    let [b' ', b' ' | b'*', name @ ..] = rest else {
        return None;
    };
    let name = if escaped {
        unescape(name)
    } else {
        name.to_vec()
    };
    (!name.is_empty()).then(|| SumLine {
        digest: lowercase_hex(hex),
        name,
    })
}

/// `SHA256 (name) = digest`, the shape `sha256sum --tag` writes.
///
/// The name goes between the first `(` and the LAST `)`: one carrying
/// parentheses inside is legal, and cutting at the first would split it.
fn bsd_line(line: &[u8]) -> Option<SumLine> {
    let rest = line.strip_prefix(b"SHA256 (")?;
    let close = rest.iter().rposition(|b| *b == b')')?;
    let (name, tail) = rest.split_at(close);
    let hex = tail.strip_prefix(b") = ")?;
    if name.is_empty() || hex.len() != SHA256_HEX || !hex.iter().all(u8::is_ascii_hexdigit) {
        return None;
    }
    Some(SumLine {
        digest: lowercase_hex(hex),
        name: name.to_vec(),
    })
}

/// Whether this line claimed to be a sum: it starts with 64 hex digits, or
/// with the BSD shape's label. A comment or a PGP header make no such
/// claim.
fn looked_like_a_sum(line: &[u8]) -> bool {
    line.starts_with(b"SHA256 (")
        || line
            .first_chunk::<SHA256_HEX>()
            .is_some_and(|hex| hex.iter().all(u8::is_ascii_hexdigit))
}

/// The hex to a `String` without going through a lossy conversion: the
/// caller already checked they are all hexadecimal digits, i.e. ASCII.
fn lowercase_hex(hex: &[u8]) -> String {
    hex.iter().map(|b| b.to_ascii_lowercase() as char).collect()
}

/// Undoes coreutils' escaping: `\\` is a backslash, `\n` a line feed and
/// `\r` a carriage return. Any other pair is left as is — inventing a
/// meaning for it would be changing the name.
fn unescape(name: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(name.len());
    let mut i = 0;
    while i < name.len() {
        match (name[i], name.get(i + 1)) {
            (b'\\', Some(b'\\')) => {
                out.push(b'\\');
                i += 2;
            }
            (b'\\', Some(b'n')) => {
                out.push(b'\n');
                i += 2;
            }
            (b'\\', Some(b'r')) => {
                out.push(b'\r');
                i += 2;
            }
            (b, _) => {
                out.push(b);
                i += 1;
            }
        }
    }
    out
}

/// The verdict of a checked line.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    /// The computed digest is the published one.
    Ok,
    /// The file is there, and is NOT what the list says.
    Mismatch,
    /// Could not be read: it is not there, or was not allowed.
    Missing,
    /// It is a directory (or something the backend does not read as a
    /// file).
    NotAFile,
    /// The name the list carries cannot be named on this system.
    ///
    /// A name with a `/` inside, an empty one, or — on Windows — one with
    /// `\` or `:`. It is its own verdict and not a "missing" because it is
    /// fixed a different way: the file may be perfectly there.
    Unnameable,
}

impl Verdict {
    /// The Fluent key it is painted with.
    #[must_use]
    pub const fn label_key(self) -> &'static str {
        match self {
            Self::Ok => "checksum-ok",
            Self::Mismatch => "checksum-mismatch",
            Self::Missing => "checksum-missing",
            Self::NotAFile => "checksum-not-a-file",
            Self::Unnameable => "checksum-unnameable",
        }
    }

    /// Whether this verdict is "checked and came out fine". Everything
    /// else — including what could not be looked at — counts as not
    /// checked.
    #[must_use]
    pub const fn is_ok(self) -> bool {
        matches!(self, Self::Ok)
    }
}

/// Compares what was published with what was computed, line by line and in
/// the SUMS FILE's order.
///
/// `computed` pairs by NAME in bytes. A name the list mentions with no
/// digest for it is [`Verdict::Missing`] — which is what has to be said: it
/// could not be checked, and that is not "fine".
///
/// The digest comparison is lowercase on both sides ([`parse_sums`] already
/// normalizes its own, and the core emits lowercase), so nothing folds
/// again here: doing it twice hides the day one of the two stops doing it.
///
/// The pairing goes by index over a map built once: with the 4096-path
/// cap, searching linearly per line is millions of vector comparisons on
/// the painting thread.
#[must_use]
pub fn verify(published: &[SumLine], computed: &[(Vec<u8>, Option<String>)]) -> Vec<Verdict> {
    let mut map: std::collections::HashMap<&[u8], Option<&str>> =
        std::collections::HashMap::with_capacity(computed.len());
    for (name, digest) in computed {
        // The FIRST one wins: a name repeated in the request was computed
        // twice with the same result, and keeping the last would say
        // nothing different.
        map.entry(name.as_slice())
            .or_insert_with(|| digest.as_deref());
    }
    published
        .iter()
        .map(
            |line| match map.get(line.name.as_slice()).copied().flatten() {
                Some(d) if d == line.digest => Verdict::Ok,
                Some(_) => Verdict::Mismatch,
                None => Verdict::Missing,
            },
        )
        .collect()
}

/// A report path, reduced to what the verdict needs: its name.
/// Converts a sums file's names into PATHS under the directory that holds
/// it, and says at which position in the request each one landed.
///
/// Returns `(paths to request, per line its position in that list)`. A
/// `None` is a name this system cannot write — with an empty component, or
/// with `\`/`:` on Windows —: it is not requested, and its verdict will be
/// [`Verdict::Unnameable`], which is not the same as "missing".
///
/// **Names with a directory are split by segment** instead of being
/// discarded: `sub/inside.txt` is what `sha256sum -r` and a `find -exec`
/// write, and are everyday sums files. The confinement comes for free and
/// deserves saying — `Segment::new` rejects `.`, `..`, empty and NUL, so a
/// hostile sums file cannot escape its directory.
///
/// Lives here and not in a frontend because it is the same decision in the
/// terminal and in the window (ADR 0077).
///
/// ```
/// use norte_frontend::checksums::{parse_sums, resolve_targets};
/// # let empty = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
/// let base = norte_proto::VPath::parse("file:///d").unwrap();
/// let lines = parse_sums(format!("{empty}  sub/x\n{empty}  ..\n").as_bytes()).lines;
/// let (paths, asked) = resolve_targets(&base, &lines);
/// assert_eq!(paths.len(), 1, "`..` is not requested");
/// assert_eq!(asked, vec![Some(0), None]);
/// ```
#[must_use]
pub fn resolve_targets(
    base: &norte_proto::VPath,
    lines: &[SumLine],
) -> (Vec<norte_proto::VPath>, Vec<Option<usize>>) {
    let mut paths: Vec<norte_proto::VPath> = Vec::with_capacity(lines.len());
    let mut asked = Vec::with_capacity(lines.len());
    for line in lines {
        let mut path = base.clone();
        let mut valid = !line.name.is_empty();
        for part in line.name.split(|b| *b == b'/') {
            // `a//b` and a trailing slash: a repeated separator names
            // nothing.
            if part.is_empty() {
                continue;
            }
            let Ok(seg) = norte_proto::Segment::new(part.to_vec()) else {
                valid = false;
                break;
            };
            path = path.join(seg);
        }
        // A name that stays in the directory itself (`.`, or all
        // separators) does not name a file inside it either.
        if valid && path == *base {
            valid = false;
        }
        if valid {
            asked.push(Some(paths.len()));
            paths.push(path);
        } else {
            asked.push(None);
        }
    }
    (paths, asked)
}

/// A report entry: its digest and — if there is none — the reason the core
/// gave, **in the order the paths were requested in**.
pub type Computed = (Option<String>, Option<norte_proto::methods::ChecksumMiss>);

/// The verdict for each line of the sums file, with the reasons already
/// distinguished (#311).
///
/// `asked` says, for each published line, at which position in the
/// REQUEST its path landed — `None` if its name cannot be written on this
/// system — and the report keeps that order. It is paired by INDEX and not
/// by name on purpose: by base name, a `SHA256SUMS` that says
/// `sub/inside.txt` — what `sha256sum -r` writes — matched nothing and came
/// out "missing" about a file that was there; and two lines with the same
/// base name in different folders would have been judged with each
/// other's digest.
///
/// ```
/// use norte_frontend::checksums::{judge, parse_sums, Verdict};
/// let empty = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
/// let pub_ = parse_sums(format!("{empty}  a\n").as_bytes()).lines;
/// let calc = vec![(Some(empty.to_owned()), None)];
/// assert_eq!(judge(&pub_, &[Some(0)], &calc), vec![Verdict::Ok]);
/// ```
#[must_use]
pub fn judge(
    published: &[SumLine],
    asked: &[Option<usize>],
    computed: &[Computed],
) -> Vec<Verdict> {
    use norte_proto::methods::ChecksumMiss;

    published
        .iter()
        .enumerate()
        .map(|(i, line)| {
            // A name this system cannot write is not a "missing": the file
            // may be there, and sending someone to look for it is sending
            // them wrong.
            let Some(Some(k)) = asked.get(i).copied() else {
                return Verdict::Unnameable;
            };
            // A position the report does not carry is a list shorter than
            // what was requested, and whoever requires `pending == 0`
            // already filtered that out: here it is "could not look",
            // never "fine".
            let Some((digest, miss)) = computed.get(k) else {
                return Verdict::Missing;
            };
            match (digest, miss) {
                (Some(d), _) if *d == line.digest => Verdict::Ok,
                (Some(_), _) => Verdict::Mismatch,
                (None, Some(ChecksumMiss::NotAFile)) => Verdict::NotAFile,
                (None, _) => Verdict::Missing,
            }
        })
        .collect()
}

/// What the bar has to say about a check.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Summary {
    /// `n` were checked and all match. **Only** when not a single line
    /// fell out: saying it over 37 of 40 is the false green this exists to
    /// prevent.
    AllOk {
        /// How many lines were checked.
        n: usize,
    },
    /// `n` do not match, are missing, or could not be looked at.
    Bad {
        /// How many did not come out fine.
        n: usize,
    },
    /// `refused` lines of the file were not even understood.
    Unreadable {
        /// How many lines got checked.
        n: usize,
        /// How many looked like sums and were not understood.
        refused: usize,
    },
}

/// What to say about these verdicts, with the lines the parser did not
/// understand outweighing everything else.
#[must_use]
pub fn summarize(verdicts: &[Verdict], refused: usize) -> Summary {
    if refused > 0 {
        return Summary::Unreadable {
            n: verdicts.len(),
            refused,
        };
    }
    let bad = verdicts.iter().filter(|v| !v.is_ok()).count();
    if bad == 0 {
        Summary::AllOk { n: verdicts.len() }
    } else {
        Summary::Bad { n: bad }
    }
}

/// What gets copied to the clipboard: one line per file in the format
/// `sha256sum -c` knows how to read, **in BYTES**.
///
/// In bytes and not in `String` because a name does not have to be text
/// (rule 1). Passing it through `String::from_utf8_lossy` put `U+FFFD`
/// into the line and `sha256sum -c` answered "no such file" about a file
/// that was there; worse, two different names that collapse to the same
/// replacement character came out as the same line twice.
///
/// A name with `\`, LF or CR comes out ESCAPED the way coreutils writes
/// it: the line carries a `\` in front and `\\`, `\n`, `\r` inside. Without
/// that, a name with a line feed split the list in two and could inject a
/// fake entry into the `SHA256SUMS` someone pastes somewhere else.
///
/// What has no digest produces no line: there is nothing to check about
/// it.
#[must_use]
pub fn to_sums_bytes(entries: &[(Vec<u8>, Option<String>)]) -> Vec<u8> {
    let mut out = Vec::new();
    for (name, digest) in entries {
        let Some(d) = digest else { continue };
        let needs_escape = name.iter().any(|b| matches!(b, b'\\' | b'\n' | b'\r'));
        if needs_escape {
            out.push(b'\\');
        }
        out.extend_from_slice(d.as_bytes());
        out.extend_from_slice(b"  ");
        if needs_escape {
            for b in name {
                match b {
                    b'\\' => out.extend_from_slice(b"\\\\"),
                    b'\n' => out.extend_from_slice(b"\\n"),
                    b'\r' => out.extend_from_slice(b"\\r"),
                    other => out.push(*other),
                }
            }
        } else {
            out.extend_from_slice(name);
        }
        out.push(b'\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const EMPTY: &str = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
    const ABC: &str = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad";

    #[test]
    fn reads_both_sha256sum_forms_and_tolerates_crlf() {
        let text = format!("{EMPTY}  texto.txt\r\n{ABC} *binario.bin\n");
        let l = parse_sums(text.as_bytes()).lines;
        assert_eq!(l.len(), 2);
        assert_eq!(l[0].name, b"texto.txt");
        assert_eq!(l[1].name, b"binario.bin", "the binary shape (`*`) too");
        assert_eq!(l[1].digest, ABC);
    }

    /// A sums file comes from OUTSIDE: comments, blank lines and junk must
    /// not bring down the check of the ones that are valid. But what
    /// LOOKED like a sum and was not understood is counted, or the summary
    /// would lie.
    #[test]
    fn it_skips_what_is_not_a_checksum_line_and_counts_what_looked_like_one() {
        let text = format!(
            "# comment\n\n-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA256\n\
             {EMPTY}  good\nzz{}  bad hex\n{EMPTY} one-space-only\n",
            &EMPTY[2..]
        );
        let read = parse_sums(text.as_bytes());
        assert_eq!(read.lines.len(), 1, "only the good one: {read:?}");
        assert_eq!(read.lines[0].name, b"good");
        assert_eq!(
            read.refused, 1,
            "the one-space-separator line carried a digest and did not fit; \
             the bad hex and the PGP headers never claimed to be sums"
        );
    }

    /// What coreutils writes when the name carries LF or a backslash.
    /// Without this the line disappeared entirely: neither checked nor
    /// listed, and the summary said "all correct".
    #[test]
    fn reads_the_escaped_coreutils_form() {
        let text = format!("\\{EMPTY}  a\\nb\n\\{ABC}  c\\\\d\n");
        let l = parse_sums(text.as_bytes()).lines;
        assert_eq!(l.len(), 2);
        assert_eq!(l[0].name, b"a\nb", "`\\n` is a real line feed");
        assert_eq!(l[1].name, b"c\\d", "`\\\\` is ONE backslash");
    }

    /// `sha256sum --tag`, which `sha256sum -c` also reads.
    #[test]
    fn reads_the_bsd_form() {
        let text = format!("SHA256 (mi (fichero).txt) = {EMPTY}\n");
        let l = parse_sums(text.as_bytes()).lines;
        assert_eq!(l.len(), 1);
        assert_eq!(
            l[0].name, b"mi (fichero).txt",
            "the name goes up to the LAST parenthesis"
        );
        assert_eq!(l[0].digest, EMPTY);
    }

    /// A file generated on Windows starts with a BOM, and that BOM ate the
    /// first line without saying anything.
    #[test]
    fn a_utf8_bom_does_not_take_the_first_line_with_it() {
        let mut bytes = b"\xEF\xBB\xBF".to_vec();
        bytes.extend_from_slice(format!("{EMPTY}  primero\n").as_bytes());
        assert_eq!(parse_sums(&bytes).lines.len(), 1);
    }

    /// A UTF-16 file (PowerShell) produces no lines, and it must be
    /// possible to say why instead of "this does not look like a sums
    /// file".
    #[test]
    fn a_utf16_file_is_recognized_as_such() {
        let mut bytes = vec![0xFF, 0xFE];
        for c in format!("{EMPTY}  x\n").encode_utf16() {
            bytes.extend_from_slice(&c.to_le_bytes());
        }
        assert!(parse_sums(&bytes).lines.is_empty());
        assert!(looks_utf16(&bytes));
    }

    /// Published uppercase, computed lowercase: it is the same hash, and
    /// saying it is not would be the worst possible false negative.
    #[test]
    fn the_digest_normalizes_to_lowercase() {
        let text = format!("{}  x\n", EMPTY.to_uppercase());
        assert_eq!(parse_sums(text.as_bytes()).lines[0].digest, EMPTY);
    }

    /// A name that is NOT UTF-8 survives the byte-by-byte parse: going
    /// through `String` would turn it into another name and the check
    /// would say "missing" about a file that is there.
    #[test]
    fn a_non_utf8_name_survives() {
        let mut line = format!("{EMPTY}  caf").into_bytes();
        line.extend_from_slice(&[0xE9, b'.', b't', b'x', b't', b'\n']);
        let l = parse_sums(&line).lines;
        assert_eq!(l.len(), 1);
        assert_eq!(l[0].name, b"caf\xE9.txt");
    }

    #[test]
    fn the_three_verdicts() {
        let published = parse_sums(format!("{EMPTY}  a\n{ABC}  b\n{EMPTY}  c\n").as_bytes()).lines;
        let computed = vec![
            (b"a".to_vec(), Some(EMPTY.to_owned())),
            (b"b".to_vec(), Some(EMPTY.to_owned())),
            (b"c".to_vec(), None),
        ];
        assert_eq!(
            verify(&published, &computed),
            vec![Verdict::Ok, Verdict::Mismatch, Verdict::Missing]
        );
    }

    /// The clipboard text is the one `sha256sum -c` knows how to read, and
    /// what has no digest does not get a made-up line.
    #[test]
    fn the_checksums_text_omits_what_has_no_digest() {
        let entries = vec![
            (b"a.txt".to_vec(), Some(EMPTY.to_owned())),
            (b"carpeta".to_vec(), None),
        ];
        assert_eq!(
            to_sums_bytes(&entries),
            format!("{EMPTY}  a.txt\n").into_bytes()
        );
    }

    /// The property that kills lossiness, the collapse of two names into
    /// one, and the injection of a forged line all at once: **for every
    /// name in the hostile corpus, what is copied reads back as the same
    /// name, byte for byte.**
    #[test]
    fn the_copy_reads_back_identical_for_the_whole_hostile_corpus() {
        for n in norte_testkit::corpus::hostile_names() {
            let entries = vec![(n.bytes.clone(), Some(EMPTY.to_owned()))];
            let bytes = to_sums_bytes(&entries);
            let read = parse_sums(&bytes);
            assert_eq!(read.refused, 0, "[{}] {}", n.id, n.why);
            assert_eq!(
                read.lines.len(),
                1,
                "[{}] a copied line is a read line: {}",
                n.id,
                n.why
            );
            assert_eq!(
                read.lines[0].name, n.bytes,
                "[{}] the name has to come back EXACT: {}",
                n.id, n.why
            );
        }
    }

    /// The specific case the property above covers and that hurts the
    /// most: two names that look the same once run through `String` are
    /// still two different lines here.
    #[test]
    fn two_names_that_collapse_in_text_do_not_collapse_here() {
        let entries = vec![
            (b"\xFF.rs".to_vec(), Some(EMPTY.to_owned())),
            (b"\xFE.rs".to_vec(), Some(ABC.to_owned())),
        ];
        let read = parse_sums(&to_sums_bytes(&entries));
        assert_eq!(read.lines.len(), 2);
        assert_ne!(
            read.lines[0].name, read.lines[1].name,
            "collapsing them would check the same file twice"
        );
    }

    /// The four reasons a line does not come out "correct" are four
    /// distinct verdicts, because they get fixed in different ways: the
    /// file is not there, it is a directory, or the name cannot be
    /// written on this system. Collapsing them into "missing" sends the
    /// reader looking in the wrong place.
    #[test]
    fn every_reason_has_its_verdict() {
        use norte_proto::methods::ChecksumMiss;

        let published = parse_sums(
            format!("{EMPTY}  ok\n{ABC}  cambiado\n{EMPTY}  ausente\n{EMPTY}  carpeta\n{EMPTY}  \0malo\n")
                .as_bytes(),
        )
        .lines;
        let asked = [Some(0), Some(1), Some(2), Some(3), None];
        let computed: Vec<Computed> = vec![
            (Some(EMPTY.to_owned()), None),
            (Some(EMPTY.to_owned()), None),
            (None, Some(ChecksumMiss::Unreadable)),
            (None, Some(ChecksumMiss::NotAFile)),
        ];
        assert_eq!(
            judge(&published, &asked, &computed),
            vec![
                Verdict::Ok,
                Verdict::Mismatch,
                Verdict::Missing,
                Verdict::NotAFile,
                Verdict::Unnameable,
            ]
        );
    }

    /// A `SHA256SUMS` that names `sub/inside.txt` — what `sha256sum -r`
    /// writes — talks about a file that is there, and pairing by BASE
    /// name gave it "missing". It is paired by position in the request.
    #[test]
    fn a_name_with_a_directory_is_judged_against_its_own_path() {
        let published =
            parse_sums(format!("{EMPTY}  sub/dentro.txt\n{ABC}  otro/dentro.txt\n").as_bytes())
                .lines;
        let computed: Vec<Computed> =
            vec![(Some(EMPTY.to_owned()), None), (Some(ABC.to_owned()), None)];
        assert_eq!(
            judge(&published, &[Some(0), Some(1)], &computed),
            vec![Verdict::Ok, Verdict::Ok],
            "two files with the same base name in different folders are each \
             judged with THEIR OWN digest"
        );
    }

    /// "All correct" cannot be said about the lines that survived the
    /// parser: the ones that fell out are exactly the odd-named ones, and
    /// those are the ones an attacker would control.
    #[test]
    fn a_line_that_was_not_understood_prevents_calling_it_green() {
        let all_ok = [Verdict::Ok, Verdict::Ok];
        assert_eq!(summarize(&all_ok, 0), Summary::AllOk { n: 2 });
        assert_eq!(
            summarize(&all_ok, 3),
            Summary::Unreadable { n: 2, refused: 3 },
            "with unreadable lines, the summary has to say so before anything else"
        );
        assert_eq!(
            summarize(&[Verdict::Ok, Verdict::Unnameable], 0),
            Summary::Bad { n: 1 },
            "what could not be looked at counts as not checked, never as fine"
        );
    }

    /// A name with a line feed must not be able to split the list nor
    /// sneak in an entry nobody computed.
    #[test]
    fn a_name_with_a_newline_does_not_inject_an_entry() {
        let hostile = format!("x\n{ABC}  forjado").into_bytes();
        let bytes = to_sums_bytes(&[(hostile.clone(), Some(EMPTY.to_owned()))]);
        let read = parse_sums(&bytes);
        assert_eq!(read.lines.len(), 1, "one entry in, one out");
        assert_eq!(read.lines[0].name, hostile);
    }
}
