[package]
name = "norte-vfs-local"
description = "Provider VFS del filesystem local (unix/windows/macos)"
license = "MIT OR Apache-2.0"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
norte-vfs.workspace = true

[lints]
workspace = true
