name = "gruvbox-dark"

[roles]
background       = { bg = "#282828" }
regular          = { fg = "#ebdbb2" }
selection           = { fg = "#282828", bg = "#83a598" }
selection-unfocused = { fg = "#ebdbb2", bg = "#504945" }
button              = { fg = "#282828", bg = "#d3869b" }
border-focus     = { fg = "#83a598", bold = true }
border-unfocused = { fg = "#928374", dim = true }
modal-border     = { fg = "#d3869b" }
status-bar       = { fg = "#282828", bg = "#83a598" }
title            = { fg = "#83a598", bold = true }
hostile-badge    = { fg = "#fb533f", bold = true } # AA: señal de seguridad, spec §6
error            = { fg = "#fb533f" } # AA sobre dark0: el bright_red #fb4934 da 4.29:1
warning          = { fg = "#fabd2f" }
info             = { fg = "#83a598" }
match            = { fg = "#282828", bg = "#fabd2f" }
pane-background       = { bg = "#3c3836" } # bg1
pane-focus-background = { bg = "#504945" } # bg2
mark                  = { bg = "#413416" } # dark blend of bright_yellow

[files.kind]
dir          = { fg = "#83a598", bold = true }
symlink      = { fg = "#8ec07c" }
executable   = { fg = "#b8bb26", bold = true }
fifo         = { fg = "#fabd2f" }
socket       = { fg = "#d3869b" }
block-device = { fg = "#fe8019" }
char-device  = { fg = "#fe8019" }

[files.ext]
zip  = { fg = "#fb4934" }
tar  = { fg = "#fb4934" }
gz   = { fg = "#fb4934" }
rs   = { fg = "#fe8019" }
toml = { fg = "#fabd2f" }
md   = { fg = "#ebdbb2" }
png  = { fg = "#d3869b" }
jpg  = { fg = "#d3869b" }
