#!/usr/bin/env bash
# Builds the home the landing screenshots show: /home/ada, inside a sandbox.
# Everything is fixed — names, sizes, dates — so two runs draw the same
# pixels and a diff of the shots means the PRODUCT changed.
#
# usage: demo-tree.sh <dir>     (<dir> becomes /home/ada under bwrap)
set -euo pipefail

root=${1:?usage: demo-tree.sh <dir>}
# The installed plugins and the consent given to them survive a rebuild: the
# consent is given by hand (scenes/approve.scene), once.
keep=$(mktemp -d)
trap 'rm -rf "$keep"' EXIT
for f in plugins plugins-state.toml; do
	[ -e "$root/.config/norte/$f" ] && mv "$root/.config/norte/$f" "$keep/"
done
rm -rf "$root"
mkdir -p "$root/.config/norte"
cp -a "$keep/." "$root/.config/norte/"
cd "$root"

# A file of <size> bytes. Random content, so archives do not compress to nothing.
blob() { mkdir -p "$(dirname "$1")"; head -c "$2" /dev/urandom >"$1"; }
text() { mkdir -p "$(dirname "$1")"; printf '%s\n' "$2" >"$1"; }
# A real image, so the viewer and the thumbnails have something to show.
img() {
	mkdir -p "$(dirname "$1")"
	# A night sky, two blurred curtains of light and a ridge: <sky>-<light>.
	local sky=${3%-*} light=${3#*-}
	magick -size 1600x1067 "gradient:#01040c-$sky" \
		\( -size 1600x1067 xc:none -fill none -stroke "$light" -strokewidth 110 \
		-draw 'bezier 0,560 420,180 980,700 1600,260' -blur 0x55 \) -composite \
		\( -size 1600x1067 xc:none -fill none -stroke "$light" -strokewidth 36 \
		-draw 'bezier 0,420 520,120 1000,520 1600,160' -blur 0x22 -channel A -evaluate multiply 0.7 +channel \) -composite \
		-fill '#02050a' -stroke none \
		-draw 'polygon 0,1067 0,860 260,760 520,880 760,720 1040,850 1300,760 1600,870 1600,1067' \
		-resize "$2^" -gravity center -extent "$2" -quality 88 "$1"
}

# --- projects/aurora: a small Rust project -------------------------------------
p=projects/aurora
text $p/Cargo.toml '[package]
name = "aurora"
version = "0.4.2"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }'
text $p/README.md '# aurora

A tiny weather station that **talks to the northern lights**.
It reads the *Kp index* and tells you when to look up.

## Quick start

```sh
cargo run --release -- --station tromsø
```

## What it measures

- geomagnetic activity (`kp_index`)
- cloud cover over the station
- the darkness of the sky

> The best night of 2026 so far: Kp 7, clear sky, −18 °C.

See [the station guide](docs/stations.md) to add yours.'
text $p/src/main.rs 'use aurora::Station;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let station = Station::open("tromsø").await?;
    for reading in station.readings().take(10) {
        println!("{reading}");
    }
    Ok(())
}'
text $p/src/lib.rs 'mod station;
pub use station::Station;'
text $p/src/station.rs '/// One place under the sky.
pub struct Station {
    name: String,
    kp_index: f32,
}'
text $p/.gitignore '/target'
text $p/stations.json '{
  "stations": [
    { "name": "Tromsø", "lat": 69.6492, "lon": 18.9553, "kp_alert": 4 },
    { "name": "Abisko", "lat": 68.3495, "lon": 18.8312, "kp_alert": 3 },
    { "name": "Reykjavík", "lat": 64.1466, "lon": -21.9426, "kp_alert": 5 }
  ],
  "refresh_seconds": 60,
  "notify": true,
  "last_storm": null
}'
text $p/Cargo.lock '# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "aurora"
version = "0.4.2"
dependencies = [
 "serde",
 "tokio",
]'
blob $p/target/release/aurora 4718592
text $p/LICENSE 'MIT License'

p=projects/landing
text $p/package.json '{ "name": "landing", "private": true }'
text $p/index.html '<!doctype html><title>landing</title>'
blob $p/assets/hero.webp 212000

# --- Photos: real images with names from everywhere -----------------------------
img "Photos/2026-01 Tromsø/aurora-001.jpg" 1600x1067 '#0b1d3a-#3ee8a2'
img "Photos/2026-01 Tromsø/aurora-002.jpg" 1600x1067 '#101030-#8a5cf6'
img "Photos/2026-01 Tromsø/aurora-003.jpg" 1600x1067 '#04121f-#22d3ee'
img "Photos/2026-01 Tromsø/fjord.jpg" 1600x1067 '#1e3a5f-#e0f2fe'
img "Photos/東京 2025/渋谷.jpg" 1600x1067 '#3b0764-#f472b6'
img "Photos/東京 2025/富士山.jpg" 1600x1067 '#0c4a6e-#fef3c7'
img "Photos/Café de Flore.jpg" 1600x1067 '#451a03-#fbbf24'
img "Photos/profile.png" 512x512 '#0f766e-#99f6e4'

# --- Music, Documents, Downloads ------------------------------------------------
blob "Music/Sigur Rós/Ágætis byrjun/01 Intro.flac" 9437184
blob "Music/Sigur Rós/Ágætis byrjun/02 Svefn-g-englar.flac" 41943040
blob "Music/Björk/Homogenic/01 Hunter.flac" 27262976
blob "Music/Björk/Homogenic/02 Jóga.flac" 31457280
text "Documents/notes ✨.md" '# Ideas

- a file manager that never loses a file
- undo for everything'
text Documents/todo.txt '[x] backup photos
[ ] renew passport
[ ] learn Norwegian'
blob Documents/invoice-2026-08.pdf 84210
blob Documents/invoice-2026-09.pdf 86112
blob "Documents/Résumé — Ada.pdf" 142331
blob Documents/budget.ods 23018
blob Downloads/debian-13.1.0-amd64-netinst.iso 67108864
blob Downloads/norte-0.3.0-alpha.4.AppImage 25165824
(cd Photos && zip -qr ../Downloads/wallpaper-pack.zip "2026-01 Tromsø")
tar -C projects -cf - aurora | zstd -q -o Downloads/aurora-backup.tar.zst
# bash's \u reads the passwd entry, not $USER: the prompt names ada by hand.
# Fonts shoot.sh fetched (a CJK one), where fontconfig looks for a user's.
if [ -d "${LANDING_SHOTS_FONTS:-}" ]; then
	mkdir -p .local/share/fonts
	cp "$LANDING_SHOTS_FONTS"/* .local/share/fonts/
fi
text .bashrc "export EDITOR=hx
PS1='\\[\\e[1;32m\\]ada@norte\\[\\e[0m\\]:\\[\\e[1;34m\\]\\w\\[\\e[0m\\]\\$ '"

# Fixed dates, newest last, so the Modified column reads like a real week.
i=0
while IFS= read -r -d '' f; do
	touch -h -d "2026-09-$((10 + i % 14)) $((8 + i % 11)):$((i * 7 % 60)):00" "$f"
	i=$((i + 1))
done < <(find . -mindepth 1 -not -path './.config*' -print0 | sort -z)
